### ISSUE TITLE
测试发现使用池计算时间并没有缩短，只有内存占用变小了。

### ISSUE THREAD

**Issue by ppmoon** [panjf2000/ants#1]
![image](https://user-images.githubusercontent.com/3971390/42390612-0f596eca-817f-11e8-975a-bb8091f5dd5a.png)
您好，我把您的代码拉倒本地，运行了测试，但是发现，测试结果和您截图结果是有差距的，只是内存占用变少了，但是计算的时间并没有您测试的那种提升，希望可以请教一下这里的原因是什么呢？

**Comment by panjf2000** [comment]
你好，我刚刚在自己的机器上又试了一下，这是结果：
![image](https://user-images.githubusercontent.com/7496278/42405000-08a2cc46-81c2-11e8-83e1-b17c21d7ec20.png)

我设置的1000w的量。事实上这个库在100w任务量的时候速度基本是和原生并发持平的（当然ants会有比较大的内存优势），甚至多次测试可能还有落后的情况，100w以下的量就基本要落后于原生并发了，因为ants其实就是利用了超大规模的go程对Go调度器造成的调度压力过大而进行资源复用得以提高性能，如果任务量不大的话Go调度器完全可以应付得过来，相反ants还要进行一些初始化和复用就显得有点多余了，1000w的话ants的性能优势就体现出来了。

另外，我记得刚开始测试的时候1000w任务量原生并发的时间基本都是往40s以上走的了，但是最近测试也有发现现在基本都在30s以下，有时候甚至在20s多，基本就比ants多几秒而已，不知道是不是和我升级了go版本有关，还有方便提供下你的机器参数和go版本吗？我这段时间再仔细研究下性能测试，还有，感谢反馈哦🙂

**Comment by ppmoon** [comment]
![image](https://user-images.githubusercontent.com/3971390/42405792-d26453a4-81ce-11e8-9062-4ba8caae5181.png)
![image](https://user-images.githubusercontent.com/3971390/42405795-d9084bac-81ce-11e8-8258-a8fa4235e82d.png)
golang版本是1.10.3 在windows上测试。
````bash
➜  ants git:(master) go test -v
=== RUN   TestDefaultPool
--- PASS: TestDefaultPool (6.79s)
	ants_test.go:51: running workers number:37796
	ants_test.go:54: memory usage:190 MB
=== RUN   TestNoPool
--- PASS: TestNoPool (5.88s)
	ants_test.go:70: memory usage:832 MB
PASS
ok  	github.com/panjf2000/ants	12.700s
````
golang版本 1.10.1 在 mac上测试
测试的都是1000w
换到mac上依然是内存占用少，但是时间上并没有提升
https://www.reddit.com/r/golang/comments/7p9juk/how_to_reuserepurpose_goroutines/
我在reddit上看到了这个。
Starting goroutines and just letting them end is generally simpler and faster than trying to do pooling yourself.

Unlike GC for memory objects, where the end-of-life is only determined during a mark-and-sweep phase, the end-of-life for goroutines is obvious once the function returns. In that situation, the runtime actually puts the goroutine stack in an internal pool. New goroutines are actually sourced from that pool.

Writing your own pool is likely to be slower and have edge cases that causes it to perform terribly.
goroutine 生命周期和一个对象的生命周期不同，可能不是按照CG回收规则来回收的。
在golang层面已经有一个内部的回收池，新建的goroutine从内部里取。如果自己实现pool很有可能会慢一点。

但是这个帖子后面也有人说复用goroutine会更快。

从你的测试结果来看，pool创建了更多的goroutine。只要数量足够多，那并发计算下来时间可能会更少。我猜测，只是猜测，可能由于我CPU更快一些，所以大量复用goroutine，产生争抢情况，复用的瓶颈影响了性能。所以时间更多一些，而你也许CPU稍微慢一点，计算周期长，所以开了大量的goroutine，所以综合来看复用的更少在执行时间上，就更短了。

希望和你共同讨论一下。共勉。

**Comment by panjf2000** [comment]
👍分析的不错，但关于复用的问题，事实上Go调度器的确有一个复用机制，每次使用`go`关键字的时候它会检查当前结构体M中的P中，是否有可用的结构体G。如果有，则直接从中取一个，否则，需要分配一个新的结构体G。如果分配了新的G，需要将它挂到runtime的相关队列中，但是调度器却没有限制goroutine的数量，这在瞬时性goroutine爆发的场景下就可能来不及复用G而依然创建了大量的goroutine，所以`ants`除了复用还做了限制goroutine数量。

所以，`ants`主要是做了数量限制，没有可用的go程就等待而不是和Go调度一样直接新开一个go程，所以我觉得在超大规模下复用还是对性能有所提升的，现在看来goroutine调度这一块还是很复杂啊，看来我也得再继续研究研究看看还有啥可以挖掘的，可以keep in touch到时候有啥心得可以互通有无哈哈😆
