### ISSUE TITLE
高并发下设定较小的worker数量问题

### ISSUE THREAD

**Issue by Moonlight-Zhao** [panjf2000/ants#10]
会存在cpu飚升的问题吧？

**Comment by panjf2000** [comment]
会导致很多任务长时间在阻塞，至于cpu飙升应该不会

**Comment by Moonlight-Zhao** [comment]
所以应该在goroutine中调用submit 否则会阻塞主任务

**Comment by panjf2000** [comment]
不是的，如果每一个submit都用一个goroutine那不就违背初衷了吗，这样的话你有多少个任务还是要启动多少个原生goroutine。

**Comment by Moonlight-Zhao** [comment]
// Submit submits a task to this pool.
func (p *Pool) Submit(task f) error {
	if len(p.release) > 0 {
		return ErrPoolClosed
	}
	p.getWorker().task <- task
	return nil
}
我是觉得p.getWorker()  阻塞不太好 ，这样主任务和pool没有彻底隔离

**Comment by liyonglion** [comment]
我觉得这个会导致cpu上升。调用Submit时，如果没有多余的worker，会一直进入这个死循环
```		for {
			p.lock.Lock()
			idleWorkers = p.workers
			l := len(idleWorkers) - 1
			if l < 0 {
				p.lock.Unlock()
				continue
			}
			w = idleWorkers[l]
			idleWorkers[l] = nil
			p.workers = idleWorkers[:l]
			p.lock.Unlock()
			break
		}```
一直会continue，直到有空闲的worker，这样会阻塞调用Submit的goroutine.

**Comment by liyonglion** [comment]
![snip20180927_3](https://user-images.githubusercontent.com/12890888/46144182-c4efe200-c28e-11e8-8e69-ffd4502e3b9e.png)

cpu占用率一直接近100%

![snip20180927_4](https://user-images.githubusercontent.com/12890888/46144221-ddf89300-c28e-11e8-985b-48437eb20cdc.png)

**Comment by panjf2000** [comment]
@liyonglion 这个例子看起来有点极端，因为只有两个任务，pool容量是1，所以剩下那个不断在自己加锁解锁导致cpu忙，如果是多个竞争的大部分是block状态，应该不会出现这种cpu满的情况，不然你把例子改改？增加提交的任务数再看看，看看还会不会出现这种情况。

**Comment by liyonglion** [comment]
@panjf2000  ants比较适合做“短期”任务，如果存在大量的“长期”任务，很有可能导致死循环。为什么不block当前Submit的“线程”？

**Comment by panjf2000** [comment]
@liyonglion 之前有用过chan阻塞等待，但是导致了一个死锁问题：#6，后来才改成这种形式。所以我说的增加submit的任务数再测试之后也是cpu 100%吗？这个问题我现在没想到比较好的解决办法，我再想想，或者你有没有比较好的想法？可以提个pr。

**Comment by liyonglion** [comment]
@panjf2000  不知道这个方案可行：chan 不是pool级别，而是任务级别。调用submit和pool之间就是一个消费模型，可以实现一个任务队列，调用Submit向队列生产任务，pool 里的worker消费任务。每个任务里面有一个chan，如果想阻塞Submit，则给该提交的任务make(chan,1)，然后block，消费到该任务的woker，判断该chan是否为nil，不为nil，这写入数据，Submit继续执行。

**Comment by liyonglion** [comment]
@panjf2000  我提交了一个pr，你看下是否合理？我自己跑了上面的用例，没有问题。效率方面我还没有具体测试。

**Comment by panjf2000** [comment]
@liyonglion 我看修改的代码应该是正确的，但是有两个问题：
1. 要正确测试你pr，你要把ants_test.go里import的路径改成你自己的路径；
2.你现在只修改了pool.go的代码，麻烦把pool_func.go里相应的地方也优化一下。
