### ISSUE TITLE
参数动态化

### ISSUE THREAD

**Issue by tsxylhs** [panjf2000/ants#101]
执行的func是否可以添加参数动态  例如  ...interface{}

**Comment by panjf2000** [comment]
把多个参数放到一个 struct 里，然后把这个 struct 转成 interface，可以解决你的需求吗？

**Comment by tsxylhs** [comment]
可以的

**Comment by tsxylhs** [comment]
可以的

**Comment by panjf2000** [comment]
动态化参数的需求一般是希望传递多个参数到 pool，目前这个需求可以通过上面所说的方式满足，短期内暂时不会支持动态化参数，因为这个会导致接口变更，按照开源软件版本更迭的规范，不向后兼容的接口变更需要升级到下一个大版本，目前 `ants` 并没有大的功能特性更新，所以不考虑升级到下一个大版本，这个功能等到下一个大版本升级的时候再带上。
