### ISSUE TITLE
求解：空闲worker回收后，为什么会重新放回sync.Pool中呢

### ISSUE THREAD

**Issue by xieao** [panjf2000/ants#102]
作者你好，在阅读源码的时候，遇到了一个问题：
一个goWorker在处理完chan中的task后，会把自身重新放回空闲的workArray中，但同时也放到了workerCache（sync.Pool）中，看了下fasthttp的实现，也做了同样的处理。在代码中我标出了这两处的位置。

```go
func (w *goWorker) run() {
	w.pool.incRunning()
	go func() {
		defer func() {
			w.pool.decRunning()
			w.pool.workerCache.Put(w) // 这里放到了cache中
			if p := recover(); p != nil {
				if ph := w.pool.options.PanicHandler; ph != nil {
					ph(p)
				} else {
					w.pool.options.Logger.Printf("worker exits from a panic: %v\n", p)
					var buf [4096]byte
					n := runtime.Stack(buf[:], false)
					w.pool.options.Logger.Printf("worker exits from panic: %s\n", string(buf[:n]))
				}
			}
		}()

		for f := range w.task {
			if f == nil {
				return
			}
			f()
			if ok := w.pool.revertWorker(w); !ok {  // 这里把空闲worker放回了workArray中
				return
			}
		}
	}()
}
```

由于goWorker是引用，所以同一个goWorker会同时存在于workerArray和sync.Pool中，会不会出现一种情况，从sync.Pool中Get的worker其实在还在有效期中，最终导致goroutine pool中运行的worker数量是”假“的，因为有两个worker是同一个

这种情况可能需要测试，并行测试较难复现我说的场景，如果您对于这块有比较好的解答，感谢~

**Comment by panjf2000** [comment]
你理解错了，只有在整个 worker goroutine 退出的时候才会放到 sync.Pool 里，而不是每次执行 task 之后都会放到 sync.Pool，看清楚，这部分逻辑是在 defer 里的。
