### ISSUE TITLE
我有个疑问,http本身就是基于goroutine实现吗？ 集成http server 有什么好处，大神们回答下呗

### ISSUE THREAD

**Issue by Xuzan9396** [panjf2000/ants#104]
我有个疑问,http本身就是基于goroutine实现吗？ 集成http server 有什么好处，大神们回答下呗

**Comment by panjf2000** [comment]
http 标准库的确是每一个连接用一个 goroutine 去处理，这里使用 ants 的确没有太大的意义，README 里的例子我也在考虑移除掉，等会儿一起更新了吧。
