### ISSUE TITLE
疑问？我用NewPoolWithFunc 创建了10个协程去处理，每个goroutine耗时需要1分钟左右,看下我的代码是不是可以这么处理

### ISSUE THREAD

**Issue by Xuzan9396** [panjf2000/ants#105]
#### 疑问？我用NewPoolWithFunc 创建了10个协程去处理，每个goroutine耗时需要1分钟左右，有一种情况，就是我的goroutine 里面可能有超时任务，不释放，我这边想处理2分钟还没结束，就结束掉这个gotoutine， 我这边代码是不是可以这么优化
```
	options := ants.Options{}
	options.ExpiryDuration = 2 * time.Minute  // 两分钟没处理完结束，释放
	p, _ := ants.NewPoolWithFunc(10, func(i interface{}) {
		// 一分钟任务
		return 
	},ants.WithOptions(options))
	p.Release()
```

**Comment by Xuzan9396** [comment]
@panjf2000

**Comment by Xuzan9396** [comment]
![image](https://user-images.githubusercontent.com/24741439/89756650-c25ea480-db15-11ea-9d5b-8fda4bf6dfaa.png)

## 执行结果

![image](https://user-images.githubusercontent.com/24741439/89756892-4add4500-db16-11ea-8718-a99e383cb9ec.png)

**Comment by mikeqoo1** [comment]
#96 

這邊可能有你需要的

**Comment by panjf2000** [comment]
`ExpiryDuration` 不是你理解的意思，这个参数表示的是 `ants` 定时清理长时间未使用的 worker，比如设置 `ExpiryDuration` 为 1 0 秒，代表内部会每过 10s 清理一遍，检查每个超过 10s 没使用过的 worker，可能是注释的意思有歧义，我等会儿更新下代码注释。

**Comment by Xuzan9396** [comment]
好的 @panjf2000
