### ISSUE TITLE
较新版本golang是否还需要ants以及类似的pool实现来替代go？

### ISSUE THREAD

**Issue by cokeboL** [panjf2000/ants#109]
```sh
# go version go1.13.1

BenchmarkGoroutines-8  3   352026800 ns/op	   14885 B/op	      39 allocs/op
BenchmarkAntsPool-8    2   581543800 ns/op	16137376 B/op	 1001286 allocs/op
```

1. 如果上游业务本身并发度较高，直接同步执行task就可以，不需要协程pool
2. 不管上游业务本身并发度是高还是低，如果想要异步task，由于较新版本的go性能和gc都表现的很不错、比pool各方面还算好些，pool与go的主要区别就是协程数量控制，go+rate limit即可，不太需要pool

**Comment by xiangjihan** [comment]
goroutine底层的GPM模型有没有实现多路复用的可能？
