### ISSUE TITLE
想问下本项目在解锁时不用defer语句的原因

### ISSUE THREAD

**Issue by FingalVon** [panjf2000/ants#112]
我阅读了本项目的代码，发现有许多需要解锁的地方没有在defer中进行unlock，而是采取了比较麻烦的——在所有的函数退出点手动unlock。想问下，我们是出于defer的性能问题而放弃了这一写法吗？如果是，在go1.13之后的版本中，defer语句有了比较明显的性能优化，如果是基于1.13之后的版本来开发这一工具，我们的开发者会倾向于选择defer语句中unlock还是手动unlock？

**Comment by panjf2000** [comment]
最早的时候的确是基于性能的考量而选择手动 unlock，不过正如你说的，defer 后来的版本里的性能的确有了很大的提升，现在也不是很有必要为了性能而手动 unlock 了，不过手动 unlock 有一个好处就是能够更细粒度地控制锁的范围，所以如果没有特别的必要，暂时还是保持现状吧。
