### ISSUE TITLE
[BUG] Memory leak

### ISSUE THREAD

**Issue by Mutated1994** [panjf2000/ants#113]
The following is my code causing a memory leak in `ants@v2.4.2`
```
package main

import (
	"fmt"
	"net/http"
	_ "net/http/pprof"
	"sync"
	"time"

	"github.com/panjf2000/ants/v2"
)

func main() {
	/**
	pprof
	http://127.0.0.1:6060/debug/pprof/
	*/
	go func() {
		_ = http.ListenAndServe("localhost:6060", nil)
	}()

	for k := 0; k < 4; k++ {
		for i := 0; i < 400; i++ {
			go DoTask()
			time.Sleep(time.Millisecond * 10)
		}
		time.Sleep(time.Second * 2)
	}
	fmt.Println("Done")

}

func DoTask() {
	pool, _ := ants.NewPool(2, ants.WithExpiryDuration(time.Second*2))

	wg := sync.WaitGroup{}

	{
		wg.Add(1)
		err := pool.Submit(func() {
			defer wg.Done()
			time.Sleep(time.Millisecond * 10)
		})
		if err != nil {
			fmt.Println(err)
		}
	}

	{
		wg.Add(1)
		err := pool.Submit(func() {
			defer wg.Done()
			time.Sleep(time.Millisecond * 10)
		})
		if err != nil {
			fmt.Println(err)
		}
	}

	wg.Wait()
	pool.Release()
}

```

### Timeline
```
------------------------------------------------------------------------------------------
CPU0 revertWorker            -> state closed -> Lock -> reset -> Unlock
------------------------------------------------------------------------------------------
CPU1 Release     -> state ok ->                                         -> Lock -> insert
------------------------------------------------------------------------------------------
```

### Consider the following:
1. `Pool.revertWorker` starts to execute (`Pool.state` is not `CLOSED`), but `Pool.revertWorker` -> `Pool.lock.Lock` has not yet been called.
2. `Pool.Release` starts to execute (`Pool.state` is `CLOSED`) and `Pool.Release` -> `Pool.lock.Lock` has been called.
3. `Pool.purgePeriodically` would break out of a loop next time.
4. `Pool.Release` -> `p.workers.reset` (clean up all workers in `workerStack.items`).
5. `Pool.revertWorker` -> `p.workers.insert`(add a worker to `workerStack.items`), but this worker would never receive any task, also leading to `goWorker.run` leaks.

However, there may be a race condition between 1 and 2.

### Note:
I tried to solve that, it seemed to work.
```
 // revertWorker puts a worker back into free pool, recycling the goroutines.
 func (p *Pool) revertWorker(worker *goWorker) bool {
-       if capacity := p.Cap(); (capacity > 0 && p.Running() > capacity) || atomic.LoadInt32(&p.state) == CLOSED {
+       if capacity := p.Cap(); capacity > 0 && p.Running() > capacity {
                return false
        }
        worker.recycleTime = time.Now()
        p.lock.Lock()

+       if atomic.LoadInt32(&p.state) == CLOSED {
+               p.lock.Unlock()
+               return false
+       }
```

# In Chinese
我们发现`Pool.revertWorker`跟`Pool.Release`存在竞态问题，会导致`goroutine`泄露。

### Timeline
```
------------------------------------------------------------------------------------------
CPU0 revertWorker            -> state closed -> Lock -> reset -> Unlock
------------------------------------------------------------------------------------------
CPU1 Release     -> state ok ->                                         -> Lock -> insert
------------------------------------------------------------------------------------------
```

如果`Release`先运行（当前池子状态未关闭往下走等锁），然后`revertWorker`也开始运行了。只要后者比前者先拿到锁`Pool.lock`，就会导致这个worker泄露。
`Release`只会给当时存在池子中的`worker`发`nil`，而这个`worker`肯定没有在池子中；然后`purgePeriodically`也会因为池子关闭而退出循环，后面`worker`过期就没人管了。除此之外好像也没有其他方法可以让泄露的`worker`退出了。

### Note:
小弟斗胆给大佬您提交一个issue，说的不对的地方还请多多指正，蟹蟹！
想跟您更加深入的讨论一下这个库，方便加下您的微信吗？小弟邮箱cainiao666999@gmail.com，可以的话我来加您😃。

**Comment by Mutated1994** [comment]
#114

**Comment by mrwh1t4** [comment]
------------------------------------------------------------------------------------------
CPU0 revertWorker            -> state closed -> Lock -> reset -> Unlock
------------------------------------------------------------------------------------------
CPU1 Release     -> state ok ->                                         -> Lock -> insert
------------------------------------------------------------------------------------------

**Comment by mrwh1t4** [comment]
------------------------------------------------------------------------------------------
CPU0 revertWorker            -> state closed -> Lock -> reset -> Unlock
------------------------------------------------------------------------------------------
CPU1 Release     -> state ok ->                                         -> Lock -> insert
------------------------------------------------------------------------------------------

**Comment by mrwh1t4** [comment]
Did the timeline get reversed？
`---------------------------------------------------------------------------------------------------------
CPU0 Release                                    -> state closed -> Lock -> reset -> Unlock
----------------------------------------------------------------------------------------------------------
CPU1 revertWorker    -> state ok ->                                                                      -> Lock -> insert
----------------------------------------------------------------------------------------------------------
`

**Comment by younger027** [comment]
> 

you are right
