### ISSUE TITLE
想请教一下，把互斥锁改成自旋锁的目的是什么呢

### ISSUE THREAD

**Issue by imxyb** [panjf2000/ants#116]
**What is your question about ants?**
Please describe your question meticulously.
如题，大概猜测是因为锁保护的代码时间非常短，使用自旋锁能够比互斥锁性能更优？

**Comment by panjf2000** [comment]
#65

**Comment by imxyb** [comment]
thanks

**Comment by imxyb** [comment]
其实我还有个疑问，golang目前的互斥锁似乎有一段是代码是先自旋几次，如果依然没有抢到锁才会进行睡眠，所以其实改了影响也不大？这里是go官方增加了spin lock的commit https://github.com/golang/go/commit/edcad8639a902741dc49f77d000ed62b0cc6956f
