### ISSUE TITLE
潘少，更新下tag吧

### ISSUE THREAD

**Issue by edcismybrother** [panjf2000/ants#12]
鄙人现在在弄dep依赖管理，有用到你写的ants项目，可是你好像忘记打最新的tag了。最新的tag 3.6是指向ed55924这个提交，git上的最新代码是af376f1b这次提交，两次提交都隔了快5个月了，看到的话，麻烦打一个最新的tag吧。（手动可怜）

**Comment by panjf2000** [comment]
我晚上回去就打一下新的tag，完了我再给你回一个邮件

edcismybrother <notifications@github.com> 于2018年9月27日周四 下午4:32写道：

**Comment by panjf2000** [comment]
tag更新了，v3.7

Andy Pan <panjf2000@gmail.com> 于2018年9月27日周四 下午5:00写道：

**Comment by edcismybrother** [comment]
@panjf2000 可以的，谢谢啦

**Comment by panjf2000** [comment]
@edcismybrother 
Hello, 我需要清理下一个`ants`的tags, 不知道对你有没有影响，如果有的话请知悉，抱歉。
