### ISSUE TITLE
提交了大量BlockingTasks，当pool.注销时，回收内存比较慢

### ISSUE THREAD

**Issue by jiangjiali** [panjf2000/ants#120]
我想知道，怎么自定义回收内存的时间

**Comment by panjf2000** [comment]
你这是属于 GC 的范畴了，目前 go 的 GC 可调参数只有一个 GOGC 环境变量，你可以去按你的需求调节。

**Comment by jiangjiali** [comment]
好呢.

**Comment by jiangjiali** [comment]
GC 触发条件
1> 当前内存分配达到一定比例则触发
2> 2 分钟没有触发过 GC 则触发 GC
3> 手动触发，调用 runtime.GC()
