### ISSUE TITLE
Some questions about pool.Tune()

### ISSUE THREAD

**Issue by PPeacHH** [panjf2000/ants#122]
i use the ants as the pool to control goroutines, and pool.Tune() can  tune pool capacity in runtime, so it is necessary to realize automatic expansion and contraction of pool? Looking forward to your answer, thank you ！
使用了ants作为pool管控goroutine， pool中也提供了一个Tune()方法可以在运行期间调整大小，那么还有必要去实现pool的自动扩缩容吗？期待你的解答，谢谢！

**Comment by panjf2000** [comment]
pool 的自动扩缩容？什么意思？

**Comment by PPeacHH** [comment]
pool 在特定的情况扩大池的容量，容量被扩大了之后，闲置时再又缩小池的容量。

**Comment by panjf2000** [comment]
> pool 在特定的情况扩大池的容量，容量被扩大了之后，闲置时再又缩小池的容量。

pool.Tune(int) 不就是来做这样的事情的吗？我还是没搞懂你的问题到底是什么？

**Comment by PPeacHH** [comment]
我的问题就是想确认pool.Tune(int)是不是可以做这样的事：

> pool 在特定的情况扩大池的容量，容量被扩大了之后，闲置时再又缩小池的容量。

你的回复已经回答了我的问题，谢谢！我当时在demo里没找到关于这个方法的使用例子，然后你的另一个开源项目gnet中也没用到它，我的同事对这个方法表示存疑，我自己是测试过了的，但我还是提出了这样一个问题🤣。
