### ISSUE TITLE
the ants goroutine pool performance 

### ISSUE THREAD

**Issue by jedrp** [panjf2000/ants#123]
**Why the perf result on my local when using ants goroutines pool doesn't like the benchmark pictures?**
I have cloned the latest code on the master branch and tried to run this command _go test -bench=. -run=none -benchmem=true_ but I got the result quite different from your benchmark pictures, the time of each test loop when using ants pool takes longer.

Here is the result on my machine:
![image](https://user-images.githubusercontent.com/23579202/98261210-cb490000-1fb6-11eb-95fb-ef28d2227234.png)

In the bench tests, I see you're using the ant pool with size 200000 to handle 1000000 tasks, so the result on my machine is what I expected because the size of the ants pool smaller than the number of tasks, so it will save the hardware resources for us but can not be faster than spawning 1000000 goroutines for that job. 

please correct me. 

Here is the detail of my environment when running the test:
_go version go1.15 darwin/amd64_
`
    Hardware Overview:

      Processor Name: 6-Core Intel Core i7
      Processor Speed: 2.6 GHz`
OS: macOS catalina

**Comment by panjf2000** [comment]
My benchmark results are a long time ago and the `go` runtime has been evolving during all the time, `go` is getting more and more performant, also, adding more and more functionalities into `ants` might have slowed it down.

**Comment by panjf2000** [comment]
Although `ants` may not beat `go` anymore, I think it's still a good choice to save the system resource and who knows, maybe in the future day I would refactor `ants` the improve its performance, making `ants` reaching `go`, even beat it again, so just stay tuned haha.

I am closing this issue, for now, thanks for bringing this up by the way.
