### ISSUE TITLE
可以使用全局变量 保存 NewPool么？

### ISSUE THREAD

**Issue by foreverZSJ** [panjf2000/ants#124]

**Comment by panjf2000** [comment]
保存 NewPool 是什么意思？

**Comment by foreverZSJ** [comment]
就是使用全局变量存储goroutine pool------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Andy&amp;nbsp;Pan&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月6日(星期五) 晚上9:18
收件人:&nbsp;&quot;panjf2000/ants&quot;<ants@noreply.github.com&gt;;
抄送:&nbsp;&quot;zsj&quot;<1043247956@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [panjf2000/ants] 可以使用全局变量 保存 NewPool么？ (#124)

**Comment by panjf2000** [comment]
这个pool本来就是应该是全局变量啊，pool不就是设计来供多线程并发使用的吗？

**Comment by panjf2000** [comment]
还有问题吗？

**Comment by foreverZSJ** [comment]
谢谢！暂时没有了。咱们有技术交流群吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andy Pan"<notifications@github.com&gt;; 
发送时间: 2020年11月12日(星期四) 上午10:00
收件人: "panjf2000/ants"<ants@noreply.github.com&gt;; 
抄送: "~~"<1043247956@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [panjf2000/ants] 可以使用全局变量 保存 NewPool么？ (#124)





 
还有问题吗？

**Comment by panjf2000** [comment]
暂时没有。
可以到 https://gitter.im/gnet-io/gnet 讨论。
