### ISSUE TITLE
About the performace when using ants in websocket 

### ISSUE THREAD

**Issue by gitmko0** [panjf2000/ants#126]
Will websocket be written with ants be more performant than using solutions such as gobwas or fastws

With reference to go routines being used in websocket here
https://www.freecodecamp.org/news/million-websockets-and-go-cc58418460bb/
and also here:
https://github.com/dgrr/fastws/

I havent tried yet but do you think ants with websocket will be faster and more performant than them for high number of connections? e.g. 1M to 10M connections using ants for websocket.

**Comment by panjf2000** [comment]
Please don't put the description in the issue title directly, which makes the issue title tedious.

Figure out the difference between title and description and put them in the right place separately.

**Comment by bashery** [comment]
gnet   >= (gobws + ants)
gnet == (evio + ants) * number of cpu
ants for manage goroutine. not for perfotmenct

**Comment by mi4tin** [comment]
websocket is not good use ant
