### ISSUE TITLE
整个项目的核心， 我的理解对不对！

### ISSUE THREAD

**Issue by Xuzan9396** [panjf2000/ants#128]
![image](https://user-images.githubusercontent.com/24741439/98886138-674e9c00-24ce-11eb-9303-48ae82158104.png)

截图所示
## 第二部分是在复用池子的基础上，控制池子的大小
不知道我理解的对不对， 最新对这块性能方面优化挺感兴趣的

**Comment by Xuzan9396** [comment]
@panjf2000

**Comment by panjf2000** [comment]
这是两种不同的 pool 的使用方式，前一个是不带参数的函数提交到 pool，后一个是提交带参数的函数的 pool，只不过前一个使用的 ants 默认的 pool，ants 会初始化一个默认的 pool，用户可以直接用，也可以自己调用 NewPool 初始化一个。

**Comment by Xuzan9396** [comment]
明白
