### ISSUE TITLE
如果任务卡主了,怎么关闭这个任务

### ISSUE THREAD

**Issue by lwydyby** [panjf2000/ants#129]
有没有什么办法主动关闭协程

**Comment by zu1k** [comment]
利用 context 机制

**Comment by lwydyby** [comment]
> 利用 context 机制，ants应该没有提供主动关闭协程的方法

但是执行到一半的情况下，是收不到context的信号的啊，只有for循环触发select那种任务才能收到信号

**Comment by zu1k** [comment]
> > 利用 context 机制，ants应该没有提供主动关闭协程的方法
> 
> 但是执行到一半的情况下，是收不到context的信号的啊，只有for循环触发select那种任务才能收到信号

不就是应该 for select嘛，没听说有什么外部的方法可以去干预一个goroutine

**Comment by panjf2000** [comment]
你说那种场景只有操作系统和硬件中断能做，比如线程切换/信号量以及硬件中断信号，那样才可能中止任务并封存上下文，转而去执行其他任务，goroutine甚至是线程都属于用户层面的，最合理的方式就是通过 context + select，如果你非要在任意时刻结束goroutine，就用信号量吧，不过不推荐。
