### ISSUE TITLE
need more examples

### ISSUE THREAD

**Issue by savixazz** [panjf2000/ants#132]
Is there any repo using ants as an example? 
ants is an amazing package , though i feel it needs more documentation and examples

**Comment by panjf2000** [comment]
I believe `ants` is a crucial library with concise APIs, besides we do have documentation: https://pkg.go.dev/github.com/panjf2000/ants/v2

**Comment by panjf2000** [comment]
As for the users of `ants`： https://github.com/panjf2000/ants#-user-cases
