### ISSUE TITLE
If ants' goroutine crash, will the whole software crash?

### ISSUE THREAD

**Issue by hiqsociety** [panjf2000/ants#135]
If ants' goroutine crash, will the whole software crash?

If so, how can we make it so that the software will still runs even if crash like erlang processes?

**Comment by panjf2000** [comment]
https://pkg.go.dev/github.com/panjf2000/ants/v2#WithPanicHandler

**Comment by hiqsociety** [comment]
Possible to show example code for the usage of the function for reference? so as to get the potential of what we can do with this ants.

thx for the software.

**Comment by panjf2000** [comment]
https://github.com/panjf2000/ants/blob/94a7a7f1cb3a11fcaaf9608c94fe1dc0bcd98ab0/ants_test.go#L238

**Comment by hiqsociety** [comment]
ok thx!
