### ISSUE TITLE
请教下怎么判断每个worker的任务是否执行完毕呢？

### ISSUE THREAD

**Issue by mayouzi** [panjf2000/ants#138]
作者你好，在`README`中，预先知道了需要执行的task个数，利用`sync.WaitGroup`去等待所有的task执行完毕

想请教下，在预先不知道task个数的情况下，怎么去知道所有的Task都执行完了呢？，伪代码如下:

```golang

type Args struct {
    ID       int
    Name string
}

func Task(args interface{}){
    param := args.(Args)
    fmt.Printf("param: %#v\n", param)
}

func main() {
    defer ants.Release()
    
    p, _ = ants.NewPoolWithFunc(10, Task)
    
    defer p.Release()

    for _, model := range queryResult {    
        args := Args {
             Name: model.Name,
             ID:       model.ID,
        }
        p.Invoke(args)
    }
    //等待所有的Task执行完毕后再结束 ？
}
```

**Comment by panjf2000** [comment]
还是用 waitgroup，循环里每次 Add(1) 不就行了？

**Comment by panjf2000** [comment]
> 这个操作只能在具体的Task里去执行done吧，如果在invoke上下文进行add和done的话，Task如果执行时间稍微长点，那wait结束的时候，并未真正执行完
> 
> ```go
> for ... {
>     wg.Add(1)
>     p.Invoke(args)
>     wg.Done()
> }
> wg.Wait()
> ```

不是很懂你的意思

**Comment by panjf2000** [comment]
另外，把 wg.Done() 放在 Task 里有什么问题？

**Comment by mayouzi** [comment]
> > 这个操作只能在具体的Task里去执行done吧，如果在invoke上下文进行add和done的话，Task如果执行时间稍微长点，那wait结束的时候，并未真正执行完
> > ```go
> > for ... {
> >     wg.Add(1)
> >     p.Invoke(args)
> >     wg.Done()
> > }
> > wg.Wait()
> > ```
> 
> 不是很懂你的意思

- 我的意思是invoke只是把task提交进pool，invoke的结束并不意味着task执行结束；
- 在task里面进行done操作倒是没有什么问题，都可以实现功能，只是想请教下ants本身是否提供了更优雅的方式去监控pool的worker执行状态(是否执行完毕等)

**Comment by panjf2000** [comment]
> 在task里面进行done操作倒是没有什么问题，都可以实现功能，只是想请教下ants本身是否提供了更优雅的方式去监控pool的worker执行状态(是否执行完毕等)

暂时没有提供这个内置功能。

**Comment by mayouzi** [comment]
> > 在task里面进行done操作倒是没有什么问题，都可以实现功能，只是想请教下ants本身是否提供了更优雅的方式去监控pool的worker执行状态(是否执行完毕等)
> 
> 暂时没有提供这个内置功能。

好的，多谢回复，祝好
