### ISSUE TITLE
Sitting idle using ants eats up to 5% cpu progressively from time to time

### ISSUE THREAD

**Issue by hiqsociety** [panjf2000/ants#140]
Sitting idle using ants eats up to 5% cpu just sitting idle from time to time.

possible to disable this eating cpu? if idle should not be eating cpu time.

**Comment by panjf2000** [comment]
https://github.com/panjf2000/ants/blob/94a7a7f1cb3a11fcaaf9608c94fe1dc0bcd98ab0/pool.go#L69-L93

There will be always a separate goroutine that runs periodical jobs to clean up idle worker goroutines, which may cause the CPU consumption but still, 5% is not an expected amount.

If you don't want this goroutine to occupy too many system resources, I'd suggest you tune the `ExpiryDuration` option:

https://github.com/panjf2000/ants/blob/94a7a7f1cb3a11fcaaf9608c94fe1dc0bcd98ab0/options.go#L21

**Comment by panjf2000** [comment]
Did you try my way? did it work for you?

**Comment by Clever-Wang** [comment]
我也是遇到了这个问题,不过更狠 cpu直接干到了 130%  不知道是不是我用法不对，网上粘贴的，还没来得及看原因。

ants 版本： github.com/panjf2000/ants v1.3.0

代码如下：
```go
const (
    goroutineCount  = 5000
)

var (
    AntsGoroutinePool  *ants.Pool
    InitResult = false
)

func init() {
   options :=  ants.Options{}
   // 是否预分配内存
   options.PreAlloc = false
   // 工作池是否是非阻塞的，这决定了 Pool.Submit 接口在提交任务时是否会被阻塞
   options.Nonblocking = true
   // 清理 goroutine 的时间间隔 (秒)
   options.ExpiryDuration = 5
   // 允许阻塞的最大限制 仅在阻塞模式下有效
   options.MaxBlockingTasks = goroutineCount
   // 发生panic时执行该函数
   options.PanicHandler = func(err interface{}) {
       log.GetTracerLogger().Error("worker exits from a panic: %+v\n", err)
   }
   var err error
   AntsGoroutinePool, err = ants.NewPool(goroutineCount, ants.WithOptions(options))
   if err != nil {
       log.GetTracerLogger().Error("初始化 goroutinePool 异常 %+v", err)
   }

   log.GetTracerLogger().Info("初始化 goroutinePool 成功 capacity:%d, running:%d, free:%d", AntsGoroutinePool.Cap(), AntsGoroutinePool.Running(), AntsGoroutinePool.Free())
   InitResult = true
}
```

**Comment by panjf2000** [comment]
你这个就太离谱了，不可能是 `ants` 的定时任务导致的，先定位一下具体占用 CPU 的进程看看。

**Comment by Clever-Wang** [comment]
是的 我把所有集成的服务代码全注释了  只留了这个  上面的所有代码 就在一个文件里面的 把init放开  就直接干到了 130%   除了引入了几个 dubbo go的 包 相当于是个空服务了，一点点排查的 别的注释打开都没事

**Comment by Clever-Wang** [comment]
那个原因 知道了 是因为 时间的问题   ExpiryDuration = 5  不对 得改成秒 才行 。
