### ISSUE TITLE
Out-of-date README, misleading terminology and stale description on high performance 

### ISSUE THREAD

**Issue by wymli** [panjf2000/ants#144]
Thanks for your great job on the project. 

I have some questions:
1. out-of-date image and code
 The image [10M tasks](https://github.com/panjf2000/ants#10m-tasks) is a misused or stale image. The bench function it called is not the same as [1M tasks](https://github.com/panjf2000/ants#1m-tasks) and [100k tasks](https://github.com/panjf2000/ants#100k-tasks). It is partly the same as the pic [benchmarks-with-poolwithfunc](https://github.com/panjf2000/ants#benchmarks-with-poolwithfunc) above.
 And I didn't see the bench function it called ,naming "BenchmarkGoroutineWithFunc","BenchmarkAntsPoolWithFunc", exists in the source code. Maybe it has already been removed from the src, or changed to "^TestAntsPoolWithFunc..."

2. About throughput and latency
 In [here](https://github.com/panjf2000/ants#throughput-it-is-suitable-for-scenarios-where-tasks-are-submitted-asynchronously-without-waiting-for-the-final-results), you describe the result as a kind of throughput,but maybe it should be more like a one-way latency (you just commit the job,and never wait it to be done)
 Throughput should be calculated like  [here](https://github.com/panjf2000/ants/blob/master/ants_benchmark_test.go#L64) , using wg.Wait() to get the total elapsed time t, and divide it to the number of goroutines committed, e.g." t / #goroutine "
 That's a clear question when facing pipeline.
 The Image [performance-summary](https://github.com/panjf2000/ants#-performance-summary) uses "Goroutine throughput benchmark" as its title, but using memory and latency as its y-label, which is confusing. Maybe "throughput" should be removed

3. About the performance,I tried to run the bench for more than 3 times, and got the following results.
The results seem to be very different from the bench in your [README](https://github.com/panjf2000/ants#benchmarks-with-pool)

About my machine&env:
```
Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz

go version go1.16.2 windows/amd64
```

3.1 Using Test
The only quoted variable `n` has been set to ` n        = 10000000 `, e.g. 10M
It seems that TestAntsPool runs slower than TestNoPool, though the memory saved is obviously huge.

```sh
PS D:\go-work\src\github.com\panjf2000\ants> go test -run=NoPool -v
=== RUN   TestNoPool
    ants_test.go:210: memory usage:789 MB
--- PASS: TestNoPool (5.04s)
PASS
ok      github.com/panjf2000/ants/v2    5.154s

PS D:\go-work\src\github.com\panjf2000\ants> go test -run="AntsPool$" -v
=== RUN   TestAntsPool
    ants_test.go:225: pool, capacity:2147483647
    ants_test.go:226: pool, running workers number:19360
    ants_test.go:227: pool, free workers number:2147464287
    ants_test.go:232: memory usage:184 MB
--- PASS: TestAntsPool (7.41s)
PASS
ok      github.com/panjf2000/ants/v2    7.528s
```

3.2 Using Benchmark
I first set the param to 1M tasks and 50k pool capacity,just like what you set in [README](https://github.com/panjf2000/ants#-benchmarks)
Here the performance is significantly higher than "without pool"
```sh
Running tool: D:\GO\bin\go.exe test -benchmem -run=^$ -bench ^(BenchmarkGoroutines)$ github.com/panjf2000/ants/v2

goos: windows
goarch: amd64
pkg: github.com/panjf2000/ants/v2
cpu: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
BenchmarkGoroutines-8   	       1	10773745800 ns/op	509732352 B/op	 1996637 allocs/op
PASS
ok  	github.com/panjf2000/ants/v2	11.616s

Running tool: D:\GO\bin\go.exe test -benchmem -run=^$ -bench ^(BenchmarkAntsPool)$ github.com/panjf2000/ants/v2

goos: windows
goarch: amd64
pkg: github.com/panjf2000/ants/v2
cpu: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
BenchmarkAntsPool-8   	       2	 712292750 ns/op	21032456 B/op	 1063341 allocs/op
PASS
ok  	github.com/panjf2000/ants/v2	2.363s
```
It is weird for me to see the different result, given the src code is nearly the same.

4. Is it OK to use a [only sleep function](https://github.com/panjf2000/ants/blob/master/ants_benchmark_test.go#L39) acting as worker?
Maybe changing the demoFunc to a CPU-bound func like the following, or a related compromise.
```go
// func demoFunc() {
// 	time.Sleep(time.Duration(BenchParam) * time.Millisecond)
// }
func demoFunc() {
	begin := time.Now()
	i := 0
	for {
		i++
		end := time.Now()
		if end.UnixNano()-begin.UnixNano() > int64(time.Millisecond)*BenchParam {
			return
		}
	}
}
```

5. However, in this [issue](https://github.com/panjf2000/ants/issues/123), you admit that the performance isn't higher than the plain goroutine anymore. Please UPDATE THE README!

If I have any error,correct me plz. That's my pleasure to see such an awesome project in saving memory alloction, avoiding unlimited goroutine constructions.

**Comment by panjf2000** [comment]
```
goos: linux
goarch: amd64
pkg: github.com/panjf2000/ants/v2
cpu: AMD EPYC 7K62 48-Core Processor
BenchmarkGoroutines-8             	       1	1199162338 ns/op	512415264 B/op	 2000288 allocs/op
BenchmarkSemaphore-8              	       3	 406725629 ns/op	80012624 B/op	 1000126 allocs/op
BenchmarkAntsPool-8               	       2	 575347056 ns/op	19885056 B/op	 1052832 allocs/op
BenchmarkGoroutinesThroughput-8   	       3	 353528828 ns/op	79976133 B/op	  999701 allocs/op
BenchmarkSemaphoreThroughput-8    	       3	 367018062 ns/op	79999285 B/op	  999991 allocs/op
BenchmarkAntsPoolThroughput-8     	       2	 519871186 ns/op	 3012452 B/op	   47154 allocs/op
PASS
ok  	github.com/panjf2000/ants/v2	11.937s
```
