### ISSUE TITLE
协程性能

### ISSUE THREAD

**Issue by cham-pin** [panjf2000/ants#145]
目前我用ants作为协程池处理并发请求, 发现协程的延迟有80~100us,  和我直接用go func的延迟差别不大. 
由于我的请求本身延迟大概500-600us, 协程的延迟比较影响性能
请问有什么可以改善的吗

**Comment by panjf2000** [comment]
ants最大的优势还是节省系统资源，如果你的业务是极度性能敏感的而且 goroutine 数量并不是很大的话，不一定非要用 ants，用 channel 简单控制一下数量也可以。

**Comment by cham-pin** [comment]
我的场景， 并发大概几十到几百，所以一定需要协程池， 但是又对延迟敏感。


| |
chenbin200818
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年4月1日 22:39，Andy ***@***.***> 写道：

ants最大的优势还是节省系统资源，如果你的业务是极度性能敏感的而且 goroutine 数量并不是很大的话，不一定非要用 ants，用 channel 简单控制一下数量也可以。

**Comment by panjf2000** [comment]
几百并发哪里需要 goroutine pool，等你成千上万 goroutine 的时候再考虑吧。
