### ISSUE TITLE
A proper way of using `sync.Cond`

### ISSUE THREAD

**Issue by fangxlmr** [panjf2000/ants#148]
Hello, there! I'd like to say this package shows great work!

According to the doc comments in [go pkg](https://golang.org/pkg/sync/#Cond), I doubt whether this is a proper way of using conditional variable, since I see no `p.cond.L.Lock()` before calling `p.cond.Wait()`. I haven't make any test, but won't be a problem there?

https://github.com/panjf2000/ants/blob/dbcb6a104f23b1a6a7521796b30515230353283e/pool.go#L244

**Comment by panjf2000** [comment]
https://github.com/golang/go/blob/go1.16.2/src/sync/cond.go#L52-L58

**Comment by fangxlmr** [comment]
Ah, I missed the `p.lock` part. Excuse me... :(
