### ISSUE TITLE
how do u pass value like goroutine?

### ISSUE THREAD

**Issue by hiqsociety** [panjf2000/ants#151]
e.g.

for i:=0; i<10000; i++ {
go func(abc uint64) {

}(i)
}

how do u do the same with ants?

**Comment by panjf2000** [comment]
doc: https://pkg.go.dev/github.com/panjf2000/ants/v2#NewPoolWithFunc

code:
https://github.com/panjf2000/ants/blob/dbcb6a104f23b1a6a7521796b30515230353283e/examples/main.go#L68-L77
