### ISSUE TITLE
Doubt about Pool.Free() / 关于 Pool.Free() 的一些疑惑

### ISSUE THREAD

**Issue by ycydsxy** [panjf2000/ants#152]
I need to know whether the goroutine pool is "full"(blocked in `Pool.Submit()`), and I found this function `Pool.Free()`, but I'm really confused about its behavior. 
```
// Free returns the available goroutines to work.
func (p *Pool) Free() int {
	return p.Cap() - p.Running()
}
```
as you commented, it returns the avaliable goroutines, but when you created a pool with a size of -1, you will get a negative  number. So only when `Pool.Free()` returns exactly zero, can I know that the pool is "full", right?

我想通过知道 goroutine 池是否已经满了（提交任务 `Pool.Submit()` 时阻塞），我找到了这个函数 `Pool.Free()`，但我对其行为有一些疑问。
```
// Free returns the available goroutines to work.
func (p *Pool) Free() int {
	return p.Cap() - p.Running()
}
```
正如你所评论的，它返回可用的goroutine，但是当你创建一个大小为 -1 的池时，你将得到一个负数。所以只有当 `Pool.Free()` 正好返回 0 时，我才能知道池已满，对吗？

**Comment by panjf2000** [comment]
-1 表示不限制，也就没有满这个概念了。

**Comment by panjf2000** [comment]
Free() 返回 0 可以满足你的需求，或者你也可以直接设置：
https://github.com/panjf2000/ants/blob/001c8b5e1b2a7c271fef351847fe1bf2caa95fc5/options.go#L33

设置了之后，如果池子满了，会直接返回 nil 而不会阻塞。

**Comment by ycydsxy** [comment]
明白了，多谢～

另外有两点：
1. -1 代表不限制这个很容易理解，但是此情况下 Free() 的返回值是 -1 - Pool.Running()，感觉有点奇怪...
2. 对于 Nonblocking 这个参数，池子满了会直接返回 ErrPoolOverload 这个 error 吧？

**Comment by panjf2000** [comment]
第一点我改一下，统一返回 -1；第二点，是的。
