### ISSUE TITLE
考虑将loopQueue的实现替换为栈

### ISSUE THREAD

**Issue by spadan** [panjf2000/ants#155]
我在使用ant的过程发现一个这样的case，当qps出现陡增时，会新增很多worker到队列中，而当流量降下来后，这些worker因为还在循环工作，且过期时间设置偏大，导致worker的goroutine一直达不到过期条件，不能被回收，此后goroutine数量一直处于高位，利用率下降。这固然有过期时间设置不合理的原因，但在设计上也存在一定缺陷，如果使用栈，worker的detach和insert都在栈顶，则能显著提高单个goroutine的利用率，栈底用不到的worker也能更及时的被回收，retrieveExpiry函数从栈底开始遍历，同样满足栈底首个元素不过期，则整个栈的元素不过期。

**Comment by chenbyby** [comment]
老哥，为什么是expiryTime := time.Now().Add(-duration)，而不是expiryTime := time.Now().Add(duration)？
按照现在的实现，revertWorker设置worker.recycleTime = time.Now()，那么expiryTime肯定大于worker.recycleTime，导致worker用了一次必定被回收。引入expiryTime不就是为了多重复利用几次吗？ 有点不明白，望解答

**Comment by panjf2000** [comment]
loopQueue 是环形队列，和栈是两回事，默认的实现是栈，你不要指定 loopQueue 就行了。
