### ISSUE TITLE
retrieveExpiry中expiryTime问题

### ISSUE THREAD

**Issue by chenbyby** [panjf2000/ants#156]
为什么是expiryTime := time.Now().Add(-duration)，而不是expiryTime := time.Now().Add(duration)？
按照现在的实现，revertWorker设置worker.recycleTime = time.Now()，那么expiryTime肯定大于worker.recycleTime，导致worker用了一次必定被回收。引入expiryTime不就是为了多重复利用几次吗？ 有点不明白，望解答

**Comment by panjf2000** [comment]
回收 workers 的时候是挑那些已经超过 duration 时长没有被取出的，所以才是 time.Now().Add(-duration)，你对源码的理解错了。

**Comment by chenbyby** [comment]
理解了，thx
