### ISSUE TITLE
期望暴露个 blockingNum 的统计数量

### ISSUE THREAD

**Issue by fufuok** [panjf2000/ants#157]
目前有：
`p.Running()`
`p.Free()`
`p.Cap()`

在并不想放开并发数的场景下，高峰时，
`p.Free()` 可能较长时间为 `0`，
此时很希望知道排队任务长度，即 `blockingNum` 数量或剩余排队数量 `options.MaxBlockingTasks` - `blockingNum`。

**Comment by fufuok** [comment]
目的是确保输出持续平滑的情况下，排队数据可观察，不被太长时间延时或被丢弃，或动态 `p.Tune(newSize)`
如果已有现成的方案，请指点。
谢谢 ants, gnet 很棒！

**Comment by panjf2000** [comment]
我理解可以用一个计数器实现你的需求？在每个任务的入口处对计数器加一，然后你用任务总数减去计数器数量应该就可以了吧。

**Comment by fufuok** [comment]
谢谢回复.
嗯, 是的, 现在是用计数器这么做的. 
我是看 ants 已经提供了 3 个指标数据方法, 如果能加上就更好了, 毕竟 blockingNum 到 MaxBlockingTasks 这一段目前对用户是黑盒.

**Comment by fufuok** [comment]
若没有太大实现意义, 请关闭它.

**Comment by panjf2000** [comment]
`blockingNum` 一开始只是个内部使用的变量，以前倒是没想到用户会希望拿到这个值，因为一开始考虑的是排队等待的数量应该是很小的，所以不需要持续去监控这个值。`blockingNum` 暴露出来倒不是不行，只是我不太清楚有多少用户有和你同样的需求，所以就先暂时不改吧，然后这个 issue 也暂时不关闭，如果有更多的用户提出需要拿到 `blockingNum`，那我再考虑去做。

**Comment by LainNetWork** [comment]
期望可以暴露出来+1

**Comment by JasonJunjian** [comment]
期望可以暴露出来+1

**Comment by edte** [comment]
期望可以暴露出来 + 1
