### ISSUE TITLE
关于panjf2000 / ants v2.0.0版本修复的问题

### ISSUE THREAD

**Issue by guoxinyu-shopee** [panjf2000/ants#159]
你好，我在v2.0.0看到如下描述
![image](https://user-images.githubusercontent.com/53163548/120149656-9df6c480-c21c-11eb-8631-9128417da5a3.png)
但是对比v1.2.0和v2.0.0的代码，我没看懂是如何解决这个问题的，或者这个问题是什么情况下会出现？
可否给我讲解一下？

**Comment by panjf2000** [comment]
抱歉，我之前没有打开这个仓库的 discussion，现在打开了，麻烦移步 https://github.com/panjf2000/ants/discussions

issue 一般是用来提 bug 或者 feature 的。

**Comment by guoxinyu-shopee** [comment]
> 抱歉，我之前没有打开这个仓库的 discussion，现在打开了，麻烦移步 https://github.com/panjf2000/ants/discussions
> 
> issue 一般是用来提 bug 或者 feature 的。

已经在discussion提问了
