### ISSUE TITLE
最新的基准测试跑过了么，比不过原生的

### ISSUE THREAD

**Issue by bingoohuang** [panjf2000/ants#166]
**What is your question about ants?**

BenchmarkAntsPool-12是BenchmarkGoroutines-12的两倍多，是我的机器不对么？还是后面代码写着写着就跑偏了？

```sh
goos: darwin
goarch: amd64
pkg: github.com/panjf2000/ants/v2
cpu: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
BenchmarkGoroutines-12              	       3	 411810402 ns/op	80012933 B/op	 1000135 allocs/op
BenchmarkSemaphore-12               	       2	 637331376 ns/op	80197720 B/op	 1002060 allocs/op
BenchmarkAntsPool-12                	       1	1023957685 ns/op	20676048 B/op	 1063831 allocs/op
BenchmarkGoroutinesThroughput-12    	       3	 403223552 ns/op	82825797 B/op	 1008366 allocs/op
BenchmarkSemaphoreThroughput-12     	       2	 627645680 ns/op	80062776 B/op	 1000637 allocs/op
BenchmarkAntsPoolThroughput-12      	       2	 936248712 ns/op	 1887088 B/op	   29047 allocs/op
PASS
ok  	github.com/panjf2000/ants/v2	80.746s
```

**Comment by panjf2000** [comment]
Duplicate #123

**Comment by panjf2000** [comment]
参考 #144 
压测代码使用 time.Sleep 现在看来太简单了，可能也不能反映出真实的场景，你要是有兴趣可以放到一些实际的场景压一下看看实际的数据，`ants` 现在主要是能节省大量的系统资源，至于性能，现在也有很多公司在线上使用，在复杂的生产环境启用大规模 goroutines 做网络服务的时候对性能是有不小提升的。

**Comment by panjf2000** [comment]
```
goos: linux
goarch: amd64
pkg: github.com/panjf2000/ants/v2
cpu: AMD EPYC 7K62 48-Core Processor
BenchmarkGoroutines-8             	       1	1199162338 ns/op	512415264 B/op	 2000288 allocs/op
BenchmarkSemaphore-8              	       3	 406725629 ns/op	80012624 B/op	 1000126 allocs/op
BenchmarkAntsPool-8               	       2	 575347056 ns/op	19885056 B/op	 1052832 allocs/op
BenchmarkGoroutinesThroughput-8   	       3	 353528828 ns/op	79976133 B/op	  999701 allocs/op
BenchmarkSemaphoreThroughput-8    	       3	 367018062 ns/op	79999285 B/op	  999991 allocs/op
BenchmarkAntsPoolThroughput-8     	       2	 519871186 ns/op	 3012452 B/op	   47154 allocs/op
PASS
ok  	github.com/panjf2000/ants/v2	11.937s
```

**Comment by GuoGuiRong** [comment]
我也出现了一样的问题,  本来想跑下官方的例子, 但是跑出来结果比较差
GUIRONGGUO-MB1:ants guirong$ go test -bench=. -run=none
goos: darwin
goarch: amd64
pkg: github.com/panjf2000/ants/v2
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkGoroutines-12                         3         384881688 ns/op
BenchmarkSemaphore-12                          2         636874541 ns/op
BenchmarkAntsPool-12                           2         704783709 ns/op
BenchmarkGoroutinesThroughput-12               3         387580849 ns/op
BenchmarkSemaphoreThroughput-12                2         624134008 ns/op
BenchmarkAntsPoolThroughput-12                 2         653369868 ns/op
PASS
ok      github.com/panjf2000/ants/v2    13.184s
GUIRONGGUO-MB1:ants guirong$
