### ISSUE TITLE
关于ants使用场景的疑问

### ISSUE THREAD

**Issue by DMwangnima** [panjf2000/ants#171]
针对大规模长连接（利用心跳机制，几乎不断），使用ants是否能带来性能提升呢？

**Comment by panjf2000** [comment]
上下文不足，你说下你打算怎么在这种场景下使用 goroutine pool？

**Comment by DMwangnima** [comment]
场景：mqtt服务器，单机支持五十万以上的长连接，除了心跳包，每条连接上的数据传输并不频繁。
像fasthttp一样每来一个conn就扔进goroutine pool，还是使用gnet来做呢？

**Comment by panjf2000** [comment]
一个长连接放一个 goroutine，连接一直不销毁，你这样该是多少个 goroutine 还是多少个，没复用，用 goroutine pool 没啥意义，用 gnet 实现吧。

**Comment by DMwangnima** [comment]
谢谢大佬解答 想模仿着fasthttp来实现 所以有这样的疑问
