### ISSUE TITLE
doing so to call invoke does a lot of memory allocations.

### ISSUE THREAD

**Issue by superdolt** [panjf2000/ants#175]
doing so to call invoke does a lot of memory allocations.

possible to replace {}Interface with [][]byte or something similar?
coz the allocation generated by using panjf is rather unbearable in high use case.

                var val [][]byte
                val = append(val,[]byte{0})
                val = append(val,[]byte{uint8(k)})
                val = append(val,[]byte{uint8(v)})
                val = append(val,[]byte{uint8(c)})
                val = append(val,kX) 
                val = append(val,b)
                pdbrpool.Invoke(&val)

**Comment by panjf2000** [comment]
Sorry, `interface{}` is for generic use cases, and why would it cause large memory allocation?

**Comment by panjf2000** [comment]
Closing it for inactivity
