### ISSUE TITLE
try heavily overload panjf with lots of locks and unlock, then u can see lock slow, semaphore issues and crash

### ISSUE THREAD

**Issue by hiqsociety** [panjf2000/ants#178]
try heavily overload panjf with lots of locks and unlock, then u can see lock slow, semaphore issues and crash

goroutine 6 [chan receive]:
github.com/panjf2000/ants/v2.(*Pool).purgePeriodically(0xc000112460)
        /root/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/pool.go:69 +0x109
created by github.com/panjf2000/ants/v2.NewPool
        /root/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/pool.go:137 +0x232

goroutine 7 [chan receive]:
github.com/panjf2000/ants/v2.(*Pool).purgePeriodically(0xc0001124d0)
        /root/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/pool.go:69 +0x109
created by github.com/panjf2000/ants/v2.NewPool
        /root/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/pool.go:137 +0x232

goroutine 21 [runnable]:
sync.runtime_SemacquireMutex(0x15f56f4, 0x0, 0x1)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0x15f56f0)
        /usr/local/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:81

**Comment by hiqsociety** [comment]
sry my issues. resolved.

**Comment by hiqsociety** [comment]
should this be added in for "in case" scenarios?
https://stackoverflow.com/questions/58008462/will-the-number-of-os-threads-spawned-by-go-process-never-decrease

**Comment by panjf2000** [comment]
Please show me some example code.
