### ISSUE TITLE
是否可以限制单一goroutine的执行时间

### ISSUE THREAD

**Issue by Alberthchang** [panjf2000/ants#179]
请问关于ants，是否有接口可以限制单一goroutine执行时间的，比如我一次性下发20000个任务，但是我池子开了100个，那如果所有的都阻塞了，是否可以设置单一goroutine在阻塞20s以后自动结束当前任务，接收新的任务？

**Comment by panjf2000** [comment]
那你在自己的 goroutine 逻辑里加一个超时逻辑不就行了？

**Comment by Alberthchang** [comment]
ok，那我自己写吧，本来想偷个懒。
