### ISSUE TITLE
go协程的理解

### ISSUE THREAD

**Issue by LinuxForYQH** [panjf2000/ants#18]
你好楼主，向您请教一个协程和线程的问题，协程基于go进程调度，线程基于系统内核调度，调度协程的过程是先调度线程后获得资源再去调度协程。"官方解释： GOMAXPROCS sets the maximum number of CPUs that can be executing simultaneously。限制cpu数，本质上是什么，限制并行数?，并行数即同时执行数量?，执行单元即线程?，即限制最大并行线程数量?"

**Comment by panjf2000** [comment]
GOMAXPROCS你可以理解成是G-P-M模型中的M的数量，也就是最大并行数。
