### ISSUE TITLE
限制每秒钟最大执行数量

### ISSUE THREAD

**Issue by likyh** [panjf2000/ants#182]
**Is your feature request related to a problem? Please describe.**
I want use this lib to request a list of URL (restapi). But it limit request speed. If I didn't comply, It will throw a error.
我想要请求一个URL列表（他们都是restapi），但是接口是有限速的，超过限速接口就会返回错误。

**Describe the solution you'd like**
So I want a speedLimit option to limit go routine run  number every second.
Maybe use channel and time.ticker to support it.
所以我希望有一个每秒最大task运行数或者最小运行时间的参数，应该可以通过使用channel或time.ticker来实现。

**Describe alternatives you've considered**
If this lib cannot support it, Maybe I'll add a time.ticker channel reciever at the head of worker function.
如果库无法提供这个参数或者不应该提供此参数的话，那么我应该会在worker函数的开头增加上time.ticker chennel的接收器来完成限制

**Comment by panjf2000** [comment]
你这个需求听起来是一个用户侧的场景，pool 本身应该是简单和纯粹的，如果有限速的需求，则可以像你说的在每一个 task函数里自己做一下就行了。
