### ISSUE TITLE
Pause API is needed in some scenario

### ISSUE THREAD

**Issue by lilien1010** [panjf2000/ants#190]
in our case, we need a `pool.Pause()` to  pause all jobs, and  use `pool.Resume()` to restart the jobs.

**Comment by panjf2000** [comment]
What did you mean by pausing and resuming jobs? I don't think that `ants` should interfer with the internal logic, or you were talking about `ants` intercepting new tasks (by `pool.Pause()`) and undoing it (by `pool.Release()`)?

**Comment by timo-klarshift** [comment]
You can simply implement Pause() and Resume() in some wrapping code. Just keep track of the state (running & paused) and if paused stop submitting new tasks to the pool (or stop reading tasks from a channel). And after resuming continue to submit tasks to the pool...
IMO this is userland logic and there is no need for this library to handle such things.
