### ISSUE TITLE
频繁通过pool.Tune方法来实现动态增加/减少协程的数量

### ISSUE THREAD

**Issue by longrbl** [panjf2000/ants#196]
大概的代码逻辑，在一个定时器内进行了通道任务的数量的统计，通过这个通道的任务数量在一定的时间，来通过pool.Tune方法调整协程池的数量， 但是经过一段时间后，通过poll.*里面提供的方法去统计当前有，多少协程和空闲协程，会出现一定的负数，

pool.Tune(100)//通道任务有200个，开启100个协程处理

pool.Tune(500)//通道任务大于1000个，调整协程数量为500

pool.Tune(10)// 通道任务小于100，就把任务调整为10协程
以此类推来实现 协程的动态调整，
假如直接从500下调到10 会有什么不可以预估的问题吗？
（后续贴代码）

**Comment by panjf2000** [comment]
贴一下测试代码？

**Comment by longrbl** [comment]
`package main

import (
	"github.com/panjf2000/ants/v2"
	"log"
	"math/rand"
	"time"
)

var taskchannel = make(chan int64, 200)

func main() {

	pool, _ := ants.NewPool(10)
	go func() {
		for true {
			cap := pool.Cap()
			rfee := pool.Free()
			runn := pool.Running()
			legtask := len(taskchannel)
			log.Println("-------------------------------------------")
			log.Println("协程池容量", cap)
			log.Println("可用协程", rfee)
			log.Println("正在运行协程", runn)
			log.Println("任务池数量", legtask)
			if legtask <= 10 && legtask >=0 {
				pool.Tune(10)
			}
			if legtask <= 50 && legtask > 10 {
				pool.Tune(50)
			}
			if legtask <= 100 && legtask >= 50 {
				pool.Tune(100)
			}
			if legtask <= 200 && legtask > 100 {
				pool.Tune(200)
			}
			time.Sleep(time.Second * 1)
		}
	}()
	go func() {
		for true {
			taskchannel <- time.Now().UnixNano()
			rand.Seed(time.Now().UnixNano())
			time.Sleep(time.Duration(rand.Intn(50)) * time.Millisecond)
		}
	}()

	for true {
		select {
		case data := <-taskchannel:
			pool.Submit(func() {
				task(data)
			})
		}
	}

}

func task(i int64) {
	rand.Seed(time.Now().UnixNano())
	time.Sleep(time.Duration(rand.Intn(3)) * time.Second)
	//log.Println("----", i)
}
`

进过一段时间 可以看到类似下面的结果,假如按照上面的代码动态调整协程池,是否会出现不可预估的问题
打印结果:可用协程 -23
2021/11/23 09:58:26 -------------------------------------------
2021/11/23 09:58:26 协程池容量 10
2021/11/23 09:58:26 可用协程 -23
2021/11/23 09:58:26 正在运行协程 33
2021/11/23 09:58:26 任务池数量 2
2021/11/23 09:58:27 -------------------------------------------

**Comment by panjf2000** [comment]
这种情况是有可能的，因为 `Tune()` 函数只是原子地修改了内部的 `capacity` 变量，`Free()` 是通过计算 `capacity` - `Running()`，有可能你调用 `Tune()` 之后还有很多正在运行的 worker 没有退出，此时调用 `Free()` 就有可能返回负数，等到那些的 worker 执行完任务之后放回 pool，超出当前 `capacity` 的 worker 们将会自动退出，此时的 `Free()` 才是正确的数值。

**Comment by panjf2000** [comment]
另外，你这种用法的确不是很好，其实你可以在调用 `NewPool(capacity)` 时就指定很大的 capacity，ants 是按需扩容的，直到达到预设的 capacity，不需要频繁地调用 `Tune()` 函数去调整 capacity。

**Comment by longrbl** [comment]
另外一个问题:假定我设置的池是100个,在执行的协程也是100个 他们任务的耗时大概是5秒, 假如我在100个协程运行的情况下,直接pool.Tune(10),这个时候会影响到在跑的100个协程立马结束吗? 还是会逐渐等待100协程完成任务最终下降到10个协程池容量

谢谢上面的解答了

**Comment by panjf2000** [comment]
> 另外一个问题:假定我设置的池是100个,在执行的协程也是100个 他们任务的耗时大概是5秒, 假如我在100个协程运行的情况下,直接pool.Tune(10),这个时候会影响到在跑的100个协程立马结束吗? 还是会逐渐等待100协程完成任务最终下降到10个协程池容量
> 
> 谢谢上面的解答了

不会立刻中止正在运行 worker，我前面已经说过了，要等到那些 worker 运行完之后才退出。
