### ISSUE TITLE
在传给Submit的task函数中调用Submit可能导致block

### ISSUE THREAD

**Issue by bigwhite** [panjf2000/ants#197]
**Describe the bug**

在传给Submit的task函数中调用Submit可能导致block

下面是一段示例代码：

```
package main

import (
	"fmt"
	"time"

	"github.com/panjf2000/ants/v2"
)

func main() {

	p, _ := ants.NewPool(100)

	for {
		p.Submit(func() {
			for i := 0; i < 3; i++ {
				p.Submit(func() {
					fmt.Println(time.Now().Unix())
				})
			}
		})
	}
}
```

在ubuntu 20.04 amd64平台，使用go 1.17版本运行上述程序，会导致程序锁住。

**To Reproduce**

在linux上运行上述程序。

**Expected behavior**

没有锁住，一直执行下去。

**Error messages/Trace logs**

**System info (please complete the following information):**
 - OS: linux
 - Go Version: 1.17
 - ants version: 2.4.6

**Additional context**

我不确认在Submit提交的task函数中再次调用Submit是否是ok的？找了ants文档，没看到写不允许在Submit中调用Submit。

另外初步分析了一下，Submit的task会被分配给pool中的worker。如果某个worker1执行task1，而task1又调用Submit task2，但task2恰好又被分给worker1，这样就锁住了。基于这个分析，我们可以很容易复现：

```
package main

import (
	"fmt"
	"time"

	"github.com/panjf2000/ants/v2"
)

func main() {
	p, _ := ants.NewPool(1)

	err := p.Submit(func() {
		fmt.Println("func in first submit...")
		err := p.Submit(func() {
			fmt.Println("submit in submit ...")
			fmt.Println(time.Now().Unix())
			fmt.Println("submit in submit ok")
		})

		if err != nil {
			fmt.Println("func in first submit err:", err)
			return
		}
		fmt.Println("func in first submit ok")
	})

	if err != nil {
		fmt.Println("first submit error:", err)
	}

	time.Sleep(5 * time.Second)
}
```

我们仅在pool中放置一个worker。这样就会导致block。

**Comment by mogakun** [comment]
100个worker都在调用submit，但是pool已经满了，要等worker释放，但是所有的worker都在等运行完自己的工作然后释放掉，但是自己的工作因为pool满了被阻塞了，一只无法释放掉。
所以应该是建议在提交的任务之中不要涉及对pool的操作之类的动作。

**Comment by panjf2000** [comment]
事实上 ants 并不禁止 Submit() 里再调用同一个 Pool 的 Submit()。

> 另外初步分析了一下，Submit的task会被分配给pool中的worker。如果某个worker1执行task1，而task1又调用Submit task2，但task2恰好又被分给worker1，这样就锁住了。

其实这里的分析不正确，worker 如果正在执行任务是不会分配给其他任务的，这里之所以会阻塞是 @mogakun 所说那样，所以只需要设置一下 Pool 无可用 worker 时不阻塞即可：
```go
p, _ := ants.NewPool(1, ants.WithNonblocking(true))
```

**Comment by bigwhite** [comment]
> 事实上 ants 并不禁止 Submit() 里再调用同一个 Pool 的 Submit()。
> 
> > 另外初步分析了一下，Submit的task会被分配给pool中的worker。如果某个worker1执行task1，而task1又调用Submit task2，但task2恰好又被分给worker1，这样就锁住了。
> 
> 其实这里的分析不正确，worker 如果正在执行任务是不会分配给其他任务的，这里之所以会阻塞是 @mogakun 所说那样，所以只需要设置一下 Pool 无可用 worker 时不阻塞即可：
> 
> ```go
> p, _ := ants.NewPool(1, ants.WithNonblocking(true))
> ```

这块感觉其实还是有些问题的。如果不设置ants.WithNonblocking(true)，我就是要阻塞。但这种阻塞应该是可以解开的。当task执行完毕后，自然可以空闲出一个goroutine来接新task。但问题就在于：如果我在Submit() 里再调用同一个 Pool 的 Submit()，一旦所有task都是这种情况，这个阻塞可能是无法解开的。

因此，是不是需要在ants文档中明确一下：如果要在submit再调用同一个pool的submit，需要设置ants.WithNonblocking(true)，并注意Submit可能返回的错误并适当处理这个错误。

**Comment by panjf2000** [comment]
> > 事实上 ants 并不禁止 Submit() 里再调用同一个 Pool 的 Submit()。
> > > 另外初步分析了一下，Submit的task会被分配给pool中的worker。如果某个worker1执行task1，而task1又调用Submit task2，但task2恰好又被分给worker1，这样就锁住了。
> > 
> > 
> > 其实这里的分析不正确，worker 如果正在执行任务是不会分配给其他任务的，这里之所以会阻塞是 @mogakun 所说那样，所以只需要设置一下 Pool 无可用 worker 时不阻塞即可：
> > ```go
> > p, _ := ants.NewPool(1, ants.WithNonblocking(true))
> > ```
> 
> 这块感觉其实还是有些问题的。如果不设置ants.WithNonblocking(true)，我就是要阻塞。但这种阻塞应该是可以解开的。当task执行完毕后，自然可以空闲出一个goroutine来接新task。但问题就在于：如果我在Submit() 里再调用同一个 Pool 的 Submit()，一旦所有task都是这种情况，这个阻塞可能是无法解开的。
> 
> 因此，是不是需要在ants文档中明确一下：如果要在submit再调用同一个pool的submit，需要设置ants.WithNonblocking(true)，并注意Submit可能返回的错误并适当处理这个错误。

我在文档里说明下。

**Comment by Macu1** [comment]
`for {
	if f := w.pool.popWaitingTask(); f != nil {
		f()
		continue
	}
	break
}`
可以加一个task队列，没有空闲worker的时候，把task push进去，worker在每次执行完任务之后，去check有没有等待的任务。有任务就取出来一个执行。队列清空之后才把自己还回去。
也就是没有空闲worker时候，把阻塞等待worker变成添加task到等待队列。
不过对于task不断膨胀的情况，最后都只能进入失败流程。
