### ISSUE TITLE
worker with func exits from a panic: sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by WyntersN** [panjf2000/ants#199]
**What is your question about ants?**
Please describe your question meticulously.
![image](https://user-images.githubusercontent.com/27792650/145157017-30598557-3105-4558-905e-d7fd11e73fb8.png)

### **ERROR**

![image](https://user-images.githubusercontent.com/27792650/145156779-48c197a9-4dc8-4ea2-84db-35c03efe1990.png)

CentOS6.9 x64      go version go1.17.3 linux/amd64

**Comment by panjf2000** [comment]
Where is the `wg.Add()`？

**Comment by WyntersN** [comment]
![image](https://user-images.githubusercontent.com/27792650/146131762-bae511fa-2e33-4cf2-ac38-66a2011c93c4.png)

I open  pool to 100


How does it feel like there's only one
It feels so slow

**Comment by panjf2000** [comment]
Use pprof to see the root cause.

**Comment by WyntersN** [comment]
潘大哥咱们都是中国人，为何不用中国话

**Comment by WyntersN** [comment]
![image](https://user-images.githubusercontent.com/27792650/146146838-5028ec6e-6f5a-42ae-96f6-993868fe27e3.png)
 传入1 2 3 4 5 6 顺序
取出的结果还是 1 2 3 4 5 6顺序
每秒都是3次计数 取出结果的时候没有被 打乱

**Comment by panjf2000** [comment]
你监控下 goroutine 数量

**Comment by WyntersN** [comment]
刚学 go 咋监控 goroutine

**Comment by WyntersN** [comment]
![image](https://user-images.githubusercontent.com/27792650/146668117-d5e666eb-b6fd-4bf9-a262-84533fb8ba0d.png)

p.Running() // print 7


我开了 300个 为啥只有 7个 goroutine
