### ISSUE TITLE
是否考虑任务支持回调函数处理失败的逻辑和任务依赖

### ISSUE THREAD

**Issue by kklinan** [panjf2000/ants#20]
#

**Comment by kklinan** [comment]
https://github.com/panjf2000/ants/blob/711dbdb7a222771ce15aaee1bb7b7c6e9731f208/pool.go#L119

**Comment by panjf2000** [comment]
这里可以讨论下，是否可以在任务函数里通过闭包的形式，将结果存入channel，满足你的需求？

**Comment by kklinan** [comment]
> 这里可以讨论下，是否可以在任务函数里通过闭包的形式，将结果存入channel，满足你的需求？

可以的。但不仅仅如此，最重要的是想得到哪条消息失败了，方便进行下次延时处理或丢回队列。

**Comment by zplzpl** [comment]
目前可以通过参数来传入消息失败的chan

**Comment by kklinan** [comment]
> 目前可以通过参数来传入处理失败的chan
> 
> type msg struct {
> ……
> Failed chan<- *msg
> }
> 
> // payload == &msg
> pool,_:= NewPoolWithFunc(10,func(payload interface{}) error{
> ……
> // 失败的话payload 发送到 Failed chan
> })
> 
> pool.Serve(msg)

我目前的做法是没有用 `NewPoolWithFunc()`，而是用的 `ants.NewPool()`，控制整个服务只有一个`pool`，所有的任务都是从大`pool`里取：

```
func (w *Worker) Register(fn func() error, opts ...Option) error {
	// w.Workers = append(w.Workers, runtime.FuncForPC(reflect.ValueOf(fn).Pointer()).Name())
	op := Op{}
	op.applyOpts(opts)

	if op.GoroutineSize > 0 {
		for i := 0; i < op.GoroutineSize; i++ {
			w.Pool.Submit(fn)
		}
	} else {
		return w.Pool.Submit(fn)
	}

	return nil
}
```
想基于这种方式来处理失败任务的逻辑。可有方式实现？

还有任务依赖也是我面临的问题，比如A任务依赖其它N个任务执行完成或者必须执行成功/失败后，触发A任务。当然解决这个问题并非必须靠`ants`框架层面实现，也可以业务实现，如果`ants`框架层面能解决是最完美的。

不知道你怎么认为。

**Comment by panjf2000** [comment]
错误返回，按照ants的设计，其实应该是异步的，目前没办法直接return error到调用的函数里，所以我觉得就算是处理也应该是异步的方式；至于任务依赖，目前想到的有两种办法：1.回调函数；2.消息通知(通过channel或消息队列)，至于是不是要把这些复杂的逻辑加到ants里，有待商榷，或者你也可以推一个pr，大家一起探讨下~~
