### ISSUE TITLE
请问使用默认 AntsPool 需要手动释放资源吗？

### ISSUE THREAD

**Issue by guowei-gong** [panjf2000/ants#200]
hi，我刚上手这个组件，这是一个新手的问题。

在我使用 ants.Submit(func() {}) 进行工作时，未手动初始化一个 pool，ants 会创建一个默认池。

在我不需要重置资源的情况下，我是否不用去考虑调用 pool.Release() 释放资源呢？或者说在什么情况下我需要释放 pool ？或许是在项目重新部署时？

**Comment by panjf2000** [comment]
> 在我不需要重置资源的情况下，我是否不用去考虑调用 pool.Release() 释放资源呢？

没看懂，说详细点。

**Comment by guowei-gong** [comment]
> > 在我不需要重置资源的情况下，我是否不用去考虑调用 pool.Release() 释放资源呢？
> 
> 没看懂，说详细点。

抱歉。我尽力描述我的问题。
pool.Release() 用于释放资源。（使用默认的池时）是否每一次使用 ant.Submit()，都需要在代码中调用 pool.Release（显式）。它们需要像 Mutex 一样，一定要成对出现吗？

**Comment by panjf2000** [comment]
`Release()` 是销毁一个 pool，你只应该在不需要使用 pool 的时候才做，如果后面还要使用，就不应该调用它。
