### ISSUE TITLE
如何设置协程池初始协程的大小的呢？有没有计算公式？

### ISSUE THREAD

**Issue by 18310983239** [panjf2000/ants#204]
**What is your question about ants?**
Please describe your question meticulously.
如何设置协程池初始协程的大小的呢？有没有计算公式？当前的机器环境4核8G

**Comment by panjf2000** [comment]
没有什么公式，按照实际业务场景设置，可以尽量设置得大一点没关系，`ants` 不会马上按照所设的容量分配内存，是按需扩容的。
