### ISSUE TITLE
请问当ants在执行CPU密集型任务时，调度时能否不打断任务？

### ISSUE THREAD

**Issue by dragon-zhang** [panjf2000/ants#208]
如果都是`CPU密集型任务`，让任务`无中断`地一直运行是最好的，而Go在1.14引入了`信号抢占机制`，每调用10ms就会打断一次计算，然后进行上下文重加载，再继续执行。在`ants`中，调度`CPU密集型`任务时，能否完全不打断任务？

**Comment by dragon-zhang** [comment]
额，放着不管？@panjf2000

**Comment by panjf2000** [comment]
ants 是一个用户态 goroutine pool，仅仅是做 goroutine 的复用，它不是调度器，这点先搞清楚，groutine 的运行调度是由底层的 go runtime 做的，所以你这个问题本身就不成立。

**Comment by dragon-zhang** [comment]
感谢解答。根据`GMP模型`，调度时可能会重组`G和M的关系`，此时就会进行`协程上下文的重加载`(我把`协程上下文的重加载`称为`打断并恢复CPU计算`)，当执行`CPU密集型任务`时，`协程上下文的重加载`发生的次数应当`越少越好`(最好1次都没有)，`协程上下文的重加载`这个动作是`go runtime`做的，不是`ants`做的。这么理解，ok的吧

**Comment by panjf2000** [comment]
对
