### ISSUE TITLE
is the latest 1.18 go routine faster than this?

### ISSUE THREAD

**Issue by hiqsociety** [panjf2000/ants#215]
is the latest 1.18 go routine faster than this?

just curious coz it seems faster etc now

**Comment by timo-klarshift** [comment]
Could you please provide a little bit more context to your question?

**Comment by alphadose** [comment]
@hiqsociety yes actually, the current implementation of goroutines (go 1.18) is such that using unlimited goroutines is faster than using a goroutine pool at the cost of extra memory

here are the benchmarks supporting that claim https://github.com/alphadose/itogami#benchmarks
