### ISSUE TITLE
What happens to Routine when it has finished? 

### ISSUE THREAD

**Issue by FeurJak** [panjf2000/ants#218]
Just wondering what happens to a routine that is invoked within an ants pool after it finishes ? 

Let say i set up an ants pool of size 10, and I've invoked 10 routines, so there should be 10 routines running within the pool.
If 1 routine has finished, is it now 9 routines running? Or are we still left with 10 routine but with 1 inactive ? 

I've setup my application to handle PubSub messages concurrently with each message handled by a function invoked in a worker pool (so 10 messages = 10 Message handler in ants pool). However I want to make sure that the ant pool frees up resources when 1 of the handler finishes.

**Comment by FeurJak** [comment]
My understanding from the docs is that, I need to set ants.WithExpiryDuration() to make sure that those finished routines are cleared out?

**Comment by panjf2000** [comment]
> My understanding from the docs is that, I need to set ants.WithExpiryDuration() to make sure that those finished routines are cleared out?

Yes, let's say you call WithExpiryDuration(500ms), then ants will check and find all those idle workers that haven't processed tasks in 500ms periodically (every 500ms).

**Comment by FeurJak** [comment]
@panjf2000  thank you!
