### ISSUE TITLE
purgePeriodically 导致阻塞

### ISSUE THREAD

**Issue by zqlpaopao** [panjf2000/ants#225]
最新版的 v2.5.0 release后 仍然 purgePeriodically 循环 导致程序阻塞 ，是我用的不对吗
Type: delay
Time: May 21, 2022 at 12:01am (CST)
Duration: 20.02s, Total samples = 40s (199.80%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) traces
Type: delay
Time: May 21, 2022 at 12:01am (CST)
Duration: 20.02s, Total samples = 40s (199.80%)
-----------+-------------------------------------------------------
       20s   runtime.selectgo
             github.com/panjf2000/ants/v2.(*Pool).purgePeriodically

**Comment by panjf2000** [comment]
代码贴一下。

**Comment by zqlpaopao** [comment]
> 
抱歉 代码不方便贴出来
相同代码 降了版本 是没有问题的

**Comment by Anderson-Lu** [comment]
我也遇到了
