### ISSUE TITLE
what about  adding a costumed UID for every task, so we can avoid repeatedly submit same task.

### ISSUE THREAD

**Issue by CormickKneey** [panjf2000/ants#235]
For example,  i have struct  Node {IP, Operation}
IP + Operation should be executed respectively at same time.
Some that will be cool if the code can work as follow:

``` golang
pool.Submit(func() {
    operationFunc(Node), generateUID(IP, Operation)
    }
) // return error if same UID is in running worker
```

**Comment by panjf2000** [comment]
I believe that this job could be easily done via a local map whose key is uid.

**Comment by CormickKneey** [comment]
> I believe that this job could be easily done via a local map whose key is uid.

Yep~ but i feel bad to introduce a extra struct in biz code to support this, a wrapped internal  feature could be better?  
lol, maybe i am just to lazy.
