### ISSUE TITLE
任务过多导致func里面参数的丢失

### ISSUE THREAD

**Issue by zoring** [panjf2000/ants#236]
按照task的类型，因为没有传递参数，所以一旦时间长，或者task套task，就会导致里面本地参数地址有可能失效，原因是回收。因为没有对象持有，所以回收

**Comment by cjf621** [comment]
> 按照task的类型，因为没有传递参数，所以一旦时间长，或者task套task，就会导致里面本地参数地址有可能失效，原因是回收。因为没有对象持有，所以回收

这个就跟闭包引用一样吧，要想保证可用性，得传参进去
