### ISSUE TITLE
为什么这里这样设计，不是循环引用么？求大佬解答

### ISSUE THREAD

**Issue by jiangjiangjiangjiangjiangjiangjiang** [panjf2000/ants#240]
这PoolWithFunc 和 goWorkerWithFunc 循环引用，没看明白为什么这样设计，求大佬解惑

![image](https://user-images.githubusercontent.com/23031644/180233032-b6d491d5-1214-476c-8ffc-af841ae93c5b.png)

**Comment by panjf2000** [comment]
这里都是在同一个 package 里，没有什么循环引用。

**Comment by jiangjiangjiangjiangjiangjiangjiang** [comment]
我理解，这里这个设计，应该是建立对应的worker和pool之间的所属关系。如果他们在不同的package是不是就不能这样设计了？这样设计的优点是？希望能够得到作者的解惑

**Comment by walkmiao** [comment]
> 我理解，这里这个设计，应该是建立对应的worker和pool之间的所属关系。如果他们在不同的package是不是就不能这样设计了？这样设计的优点是？希望能够得到作者的解惑

只要循环引用了就不能这样设计，这样设计不就是因为goWorkerWithFunc也用到了PollWithFunc吗。go中有非常多的这样设计，gin框架里也有
