### ISSUE TITLE
请问V1和v2的区别？

### ISSUE THREAD

**Issue by 519610446** [panjf2000/ants#242]
**What is your question about ants?**
Please describe your question meticulously.

**Comment by panjf2000** [comment]
主要是有一些不兼容的更新，还有后面有一些新的 API 和优化。

**Comment by 519610446** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by 519610446** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
