### ISSUE TITLE
提议：新增 ReleaseWaitAllWorkersExit()，用于等待所有worker都被释放后再返回

### ISSUE THREAD

**Issue by cuishuang** [panjf2000/ants#244]
由于ants中var defaultAntsPool, _ = NewPool(DefaultAntsPoolSize)，会在使用到该库的项目初始化时，先于项目的main.go执行，从而会多出一个协程； 

很多项目单测中集成了go.uber.org/goleak，用于检测goroutine泄露，从而会导致测试失败，如下图：

![image](https://user-images.githubusercontent.com/15921519/183029685-15df0f79-c45f-450e-8a34-82fa038233e7.png)

查看ants代码，发现有一个Release()方法，可以释放掉worker，但释放需要一定时间，只能休眠一个足够长的时间(经验值是1s左右)

![image](https://user-images.githubusercontent.com/15921519/183030461-d9a833b5-5454-4049-8489-2cd251cc696f.png)

![image](https://user-images.githubusercontent.com/15921519/183030267-a8860a88-14c2-449d-8911-6cc0ca01d29a.png)

建议新增一个 ReleaseWaitAllWorkersExit()方法，调用后，确保所有worker都释放后才返回

![image](https://user-images.githubusercontent.com/15921519/183030786-788a8df6-4123-4f62-befb-1454b8dbef9a.png)

另外几个可能相关的issue：

https://github.com/panjf2000/ants/issues/212

https://github.com/panjf2000/ants/issues/225 

---

related pr：https://github.com/panjf2000/ants/pull/245

**Comment by panjf2000** [comment]
现在已经有了：https://pkg.go.dev/github.com/panjf2000/ants/v2#Pool.ReleaseTimeout

**Comment by cuishuang** [comment]
恩，ReleaseWaitAllWorkersExit()就是参照的这个ReleaseTimeout；但ReleaseTimeout有两个问题：1是依然需要传入一个timeout的入参，无法做到准确的结束所有worker后就返回；2是没有在ants.go里封装一个可对外暴露的方法，defaultAntsPool无法直接调用

**Comment by cuishuang** [comment]
> 现在已经有了：https://pkg.go.dev/github.com/panjf2000/ants/v2#Pool.ReleaseTimeout

恩，ReleaseWaitAllWorkersExit()就是参照的这个ReleaseTimeout；但ReleaseTimeout有两个问题：1是依然需要传入一个timeout的入参，无法做到准确的结束所有worker后就返回；2是没有在ants.go里封装一个可对外暴露的方法，defaultAntsPool无法直接调用

**Comment by lifei6671** [comment]
> 现在已经有了：https://pkg.go.dev/github.com/panjf2000/ants/v2#Pool.ReleaseTimeout

确实有这个需求，需要等待所有正在执行的协程都退出了，主进程才退出，目前只能猜测可能的退出时间.

**Comment by HaiboLee** [comment]
需求+1 比如需要等到所有协程执行结果后再往下执行 最好设置个通道 等所有协程执行结束后通知

**Comment by cuishuang** [comment]
> 需求+1 比如需要等到所有协程执行结果后再往下执行 最好设置个通道 等所有协程执行结束后通知

我都忘了咋回事了(捂脸)
