### ISSUE TITLE
how is p.Release() behavior?

### ISSUE THREAD

**Issue by tesarwijaya** [panjf2000/ants#249]
**What is your question about ants?**
Please describe your question meticulously.

Hi, I just wondered how p.Release() behavior actually. let say i have this following simple program. we create pool p then submit busyFn which would take 10s to complete to the pool and then after 5s we send terminate signal.
```go
package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/panjf2000/ants/v2"
)

func main() {
	p, _ := ants.NewPool(ants.DefaultAntsPoolSize)

	shutdown := make(chan os.Signal, 1)
	signal.Notify(shutdown, syscall.SIGINT, syscall.SIGTERM, syscall.SIGKILL)

	p.Submit(func() {
		busyFn()
	})

	after := time.After(5 * time.Second)

	<-after

	shutdown <- syscall.SIGTERM

	<-shutdown

	fmt.Println("releasing worker...")
	p.Release()

	fmt.Println("done")
}

func busyFn() {
	ticker := time.NewTicker(1 * time.Second)
	done := make(chan bool)

	go func() {
		i := 0
		for {
			select {
			case <-done:
				fmt.Println("busyFn done")
				return
			case <-ticker.C:
				i++
				fmt.Println("busyFn Tick at", i)
			}
		}
	}()

	time.Sleep(10 * time.Second)
	ticker.Stop()
	done <- true
}
```

based on your comment [here](https://github.com/panjf2000/ants/issues/73#issuecomment-573730817), p.Release should be waiting the task in pool to complete before terminate the program, but the log show different behavior here:
```
busyFn Tick at 1
busyFn Tick at 2
busyFn Tick at 3
busyFn Tick at 4
busyFn Tick at 5
releasing worker...
done
```
p.Release() does not waiting busyFn to be done. Am i missing something?

env:
go version: 1.18
ants version: v2.5.0

**Comment by panjf2000** [comment]
Sorry for the delay.

As for your question, I think that you misread my comment from #73, calling `p.Release()` will not wait for all workers to exit, it only cleans up those idle workers and returns, and those active workers will be released once `revertWorker()` is called. If you want to wait for all workers to exit, try [ReleaseTimeout](https://pkg.go.dev/github.com/panjf2000/ants/v2#PoolWithFunc.ReleaseTimeout)

**Comment by tesarwijaya** [comment]
no problem, thank you for your response. 
honestly i just did little dive to the code while waiting for your response 😅  and understood that p.Release() is not waiting for any worker to exit but keep this issue open to clarify what i found in the code. also ReleaseTimeout is what i need, thank you again for your response and suggestion. keep up the good works! I'll close this issue.
