### ISSUE TITLE
use example errors

### ISSUE THREAD

**Issue by jiashiwen** [panjf2000/ants#25]
./antstest.go:37:14: cannot use syncCalculateSum (type func()) as type ants.f in argument to ants.Submit
./antstest.go:45:35: cannot use func literal (type func(interface {})) as type ants.pf in argument to ants.NewPoolWithFunc

**Comment by panjf2000** [comment]
@jiashiwen 
It works on my side, pls make sure that you run it on top of the latest code, thanks.
