### ISSUE TITLE
Add option to turn off purgePeriodically

### ISSUE THREAD

**Issue by czs007** [panjf2000/ants#252]
**Is your feature request related to a problem? Please describe.**

In some scenarios, I need to bind thread in the coroutine, so if the coroutine is destroyed by the timeout mechanism, the benefits of bindthread are lost.

**Describe the solution you'd like**
Add an option to turn off purgePeriodically.

**Describe alternatives you've considered**
Consider setting the timeout very large, but that's a bit tricky.

**Additional context**
The os.LockOSThread() mechanism is mostly useful when Go has to interface with some foreign library (a C library for instance). It guarantees that several successive calls to this library will be done in the same thread.
https://stackoverflow.com/questions/25361831/benefits-of-runtime-lockosthread-in-golang

**Comment by panjf2000** [comment]
You surely can call `runtime.LockOSThread()` in your task function which is submitted to `ants.Pool`, but after that task is done, how do you manage to ensure that your new task can be processed by that exact previous goroutine in pool?

**Comment by bigsheeper** [comment]
> You surely can call `runtime.LockOSThread()` in your task function which is submitted to `ants.Pool`, but after that task is done, how do you manage to ensure that your new task can be processed by that exact previous goroutine in pool?

Actually, all the os threads would be bound in `ants.Pool`, we don't care if the new task is processed by the specified goroutine, as long as the task is processed by one of the goroutines in the pool, and these goroutines should never be unbound.

**Comment by czs007** [comment]
> You surely can call `runtime.LockOSThread()` in your task function which is submitted to `ants.Pool`, but after that task is done, how do you manage to ensure that your new task can be processed by that exact previous goroutine in pool?

@panjf2000
In particular, every call to cgo, even within a single goroutine, might happen on a different OS thread.
In our usage scenario, cgo will call openmp, thus creating an openmp thread pool attached to this thread, and the openmp thread pool will not disappear with the destruction of the coroutine. If these coroutines are not bound, it will cause a lot of system threads at the end.
