### ISSUE TITLE
[Feature] Introduce the Future(like java) into ants.  

### ISSUE THREAD

**Issue by brotherlu-xcq** [panjf2000/ants#256]
**Is your feature request related to a problem? Please describe.**
在业务开发的场景中，多线程异步查询然后聚合结果的场景十分常见。java里面有submit方法可以返回一个Future对象给用户去阻塞获取业务执行结果，是否也可以在ants中引入同样的功能。

**Describe the solution you'd like**
ants新增Future，已经类似java的submit方法。

**Describe alternatives you've considered**
no

**Additional context**
如果有必要的话，我想尝试一下加这个功能。

**Comment by panjf2000** [comment]
用 channel 不就可以解决吗？

**Comment by brotherlu-xcq** [comment]
可以解决，这个出发点只是想把这个阻塞获取的通用逻辑下沉到ants。java里面的线程池submit返回的future对象，实际也是对原始的execute进行封装，来让用户更方便使用。

**Comment by panjf2000** [comment]
经过考虑，因为 Go 已经提供了 chan 这样简便的工具可以用了，我觉得没必要在 `ants` 里再封装一遍了，我认为对于 `ants` 这样轻量的开源库来说，需要专注于那些更核心的功能，弄太多『语法糖』一样的特性可能会把一个轻量的东西搞得越来越复杂，这与 `ants` 的设计初衷不符，抱歉。
