### ISSUE TITLE
[Feature]: Support resource partition 

### ISSUE THREAD

**Issue by huanggze** [panjf2000/ants#262]
### Description of new feature

I would like all worker goroutine share a pool, but partitioned according to worker tag.

### Scenarios for new feature

Resources are partitioned within the pool. So there is always some pool capacity reserved for  worker goroutines for certain tasks

### Breaking changes or not?

Yes

### Alternatives for new feature

None.

### Additional context (optional)

None.

**Comment by panjf2000** [comment]
What's the problem with setting up multiple pools for different types of tasks?

**Comment by huanggze** [comment]
sounds reasonable, thanks I will give it a try first
