### ISSUE TITLE
为何goroutine一直上不去，用户量也打不上去

### ISSUE THREAD

**Issue by liliang8858** [panjf2000/ants#27]
为何goroutine一直上不去，用户量也打不上去
是我用的有问题吗？

websocket server
https://github.com/im-ai/pushm/blob/master/learn/goroutine/goroutinepoolwebsocket.go

websocket cient
https://github.com/im-ai/pushm/blob/master/learn/goroutine/goroutinepoolwebsocketclient.go

**Comment by panjf2000** [comment]
server接收的并发请求量有多大？

**Comment by jeevi-cao** [comment]
我在本地测试  使用池比原生协程  内存占用低了 执行时间相对原生协程较慢
