### ISSUE TITLE
[Question]: 清理过期worker一点疑问

### ISSUE THREAD

**Issue by xiaozhang902** [panjf2000/ants#272]
### Questions with details

p.Running() == 0并且还有task等待唤醒 是什么场景
如果只写(p.Waiting() > 0 && p.Free() > 0)这个判断够不够

### Code snippets (optional)

```go
// There might be a situation where all workers have been cleaned up(no worker is running),
// or another case where the pool capacity has been Tuned up,
// while some invokers still get stuck in "p.cond.Wait()",
// then it ought to wake all those invokers.
if p.Running() == 0 || (p.Waiting() > 0 && p.Free() > 0) {
         p.cond.Broadcast()
}
```

**Comment by panjf2000** [comment]
> p.Running() == 0并且还有task等待唤醒 是什么场景

比如某一个调用者的流程走到了 `p.cond.Wait()`，此时有一个 worker 执行完任务放回池子，但是 `p.cond.Signal()` 比 `p.cond.Wait()` 更早执行，则会错误通知消息，而如果碰巧其他 worker 里的任务执行时间比较长，超过了定期清理的时间周期或者没有其他 worker 了，那么这个唯一的 worker 可能会被清理掉，则后面阻塞在 `p.cond.Wait()` 上的调用者就会一直阻塞住。

> 如果只写(p.Waiting() > 0 && p.Free() > 0)这个判断够不够

这里的判断现在看来确实可以优化一下
