### ISSUE TITLE
[Bug]: go.mod 中的go version(1.13)和ants.go存在不匹配

### ISSUE THREAD

**Issue by piaodazhu** [panjf2000/ants#274]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations on this issue but still have no clue.
- [X] I've searched the current list of Github issues but didn't find any duplicate issues that have been solved.
- [X] I've searched the internet with this issue, but haven't found anything helpful.

### What happened?

go.mod中要求的最低版本是1.13，而ants.go存在如下代码：
```go
defaultLogger = Logger(log.New(os.Stderr, "[ants]: ", log.LstdFlags|log.Lmsgprefix|log.Lmicroseconds))
```
事实上，go 1.13版本还不支持log.Lmsgprefix这个属性，它是go 1.14以后的。
如果在代码中删除这个属性，会影响现有的log格式；如果修改go.mod，则会导致有些用户可能遇到后续ants版本不兼容；也可以去手动实现这个属性。由于不想贸然决定，所以提了这个bug。

发现这个问题的起因是我的项目用到了ants，go.mod里面的version设置的也是1.13，但是由于本地go version版本很高，构建一切正常。我在github action中有一个job是构建并测试我的包，选取go version为1.13时，就会无法通过该测试：
```
Run go test ./... -v
go: downloading github.com/panjf2000/ants/v2 v2.7.3
go: downloading github.com/google/uuid v1.3.0
go: extracting github.com/google/uuid v1.3.0
go: extracting github.com/panjf2000/ants/v2 v2.7.3
go: finding github.com/google/uuid v1.3.0
go: finding github.com/panjf2000/ants/v2 v2.7.3
# github.com/panjf2000/ants/v2
Error: ../../../go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.3/ants.go:8[5](https://github.com/piaodazhu/gotcc/actions/runs/4907715739/jobs/8762999712#step:4:6):[7](https://github.com/piaodazhu/gotcc/actions/runs/4907715739/jobs/8762999712#step:4:8)0: undefined: log.Lmsgprefix
FAIL	github.com/piaodazhu/gotcc [build failed]
FAIL
Error: Process completed with exit code 2.
```

### Major version of ants

v2

### Specific version of ants

v2.7.3

### Operating system

Linux

### Relevant log output

```shell
Run go test ./... -v
go: downloading github.com/panjf2000/ants/v2 v2.7.3
go: downloading github.com/google/uuid v1.3.0
go: extracting github.com/google/uuid v1.3.0
go: extracting github.com/panjf2000/ants/v2 v2.7.3
go: finding github.com/google/uuid v1.3.0
go: finding github.com/panjf2000/ants/v2 v2.7.3
# github.com/panjf2000/ants/v2
Error: ../../../go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.3/ants.go:8[5](https://github.com/piaodazhu/gotcc/actions/runs/4907715739/jobs/8762999712#step:4:6):[7](https://github.com/piaodazhu/gotcc/actions/runs/4907715739/jobs/8762999712#step:4:8)0: undefined: log.Lmsgprefix
FAIL	github.com/piaodazhu/gotcc [build failed]
FAIL
Error: Pr
```

### How to Reproduce

1. Install go version 1.13 in your environment.
2. Import ants in your project.
3. Build or Run. It should failed.

### Does this issue reproduce with the latest release?

It can reproduce with the latest release

**Comment by panjf2000** [comment]
谢谢帮忙发现这个问题。

我觉得现在暂时先在 ants.go 里自定义一个 `log.Lmsgprefix` 的值 64 吧，这样也不影响 go1.13 版本，因为这个版本里也不会处理这个新值的数据位。有兴趣的话可以提一个 PR。
