### ISSUE TITLE
[Question]: How can I verifier the max goroutine count in pool is correct

### ISSUE THREAD

**Issue by mingregister** [panjf2000/ants#277]
### Questions with details

I use the ants pool as the following snappet.   
```go
type taskFunc func()

const (
	DataSize    = 10000
	DataPerTask = 100
)

func taskFuncWrapper(nums []int, i int, sum *int, wg *sync.WaitGroup, t *testing.T) taskFunc {
	return func() {
		for _, num := range nums[i*DataPerTask : (i+1)*DataPerTask] {
			*sum += num
		}

		t.Logf("task:%d sum:%d\n", i+1, *sum)
		wg.Done()
	}
}

func TestAntsPool(t *testing.T) {
	p, _ := ants.NewPool(10)
	defer p.Release()

	nums := make([]int, DataSize)
	for i := range nums {
		nums[i] = rand.Intn(1000)
	}

	var wg sync.WaitGroup
	defer wg.Wait()
	wg.Add(DataSize / DataPerTask)
	partSums := make([]int, DataSize/DataPerTask)
	for i := 0; i < DataSize/DataPerTask; i++ {
		p.Submit(taskFuncWrapper(nums, i, &partSums[i], &wg, t))
	}
}
```

My Question is: How can I verifier the max goroutine count in pool is correct. 

What had I try:
1. I was try to get the goroutineid to vierifier this.  But after google this, I found out it is very difficult to get the goroutineid.

**Comment by xyhubl** [comment]
func GoID() int {
	var buf [64]byte
	n := runtime.Stack(buf[:], false)
	idField := strings.Fields(strings.TrimPrefix(string(buf[:n]), "goroutine "))[0]
	id, err := strconv.Atoi(idField)
	if err != nil {
		panic(fmt.Sprintf("cannot get goroutine id: %v", err))
	}
	return id
}

you can try

**Comment by xyhubl** [comment]
`func GoID() int {
	var buf [64]byte
	n := runtime.Stack(buf[:], false)
	idField := strings.Fields(strings.TrimPrefix(string(buf[:n]), "goroutine "))[0]
	id, err := strconv.Atoi(idField)
	if err != nil {
		panic(fmt.Sprintf("cannot get goroutine id: %v", err))
	}
	return id
}`
you can try it

**Comment by xyhubl** [comment]
```go
func GoID() int {
	var buf [64]byte
	n := runtime.Stack(buf[:], false)
	idField := strings.Fields(strings.TrimPrefix(string(buf[:n]), "goroutine "))[0]
	id, err := strconv.Atoi(idField)
	if err != nil {
		panic(fmt.Sprintf("cannot get goroutine id: %v", err))
	}
	return id
}
you can try it
