### ISSUE TITLE
[Question]: 为什么不提供一个任务包装，等待，获取任务结果

### ISSUE THREAD

**Issue by zundaren** [panjf2000/ants#280]
### Questions with details

taskwrap = pool.submit(task)
taskwrap = pool.submit(task)
taskwrap = pool.submit(task)

添加一组等待 Task.wait([]task{})
添加待 taskwrap.wait()

var result = taskwrap.getresult()

**Comment by panjf2000** [comment]
因为  go 的 chan 已经够方便的了。
