### ISSUE TITLE
任务传参

### ISSUE THREAD

**Issue by prprprus** [panjf2000/ants#29]
你好，你的项目太酷了👍

https://github.com/panjf2000/ants/blob/master/pool.go#L124 貌似不支持带参数的任务, 请问传参是用闭包的方式吗?

**Comment by panjf2000** [comment]
@prprprus 
https://github.com/panjf2000/ants/blob/master/pool_func.go#L103, 是支持传参的。

**Comment by prprprus** [comment]
好的，🙏
