### ISSUE TITLE
[Question]: ants.Submit() question

### ISSUE THREAD

**Issue by hiqsociety** [panjf2000/ants#294]
### Questions with details

is this ok?
will ipAddrStr be sent inside ants.Submit's somefunc()?
i'm worried if ipAddrString will be ""
is the below the right way to do it?

```
func main() {
   ... //ipAddr

   go somefunc2(ipAddr)
}

func somefunc2(ipAddr netip.Addr) {
ipAddrStr := ipAddr.String()

ants.Submit(func() {
 somefunc(ipAddrStr)
})
}
```

**Comment by panjf2000** [comment]
Why would the `ipAddrString` be empty?

**Comment by hiqsociety** [comment]
1. @panjf2000 will the value of ipAddrStr change?

2. what about this?

func main() {
   ... //ipAddr

   ants.Submit(func() {
    somefunc2(ipAddr.String())
   })
}

func somefunc2(ipAddrStr string) {
ants.Submit(func() {
 somefunc(ipAddrStr)
})
}

**Comment by panjf2000** [comment]
Again, why would the value change? I don't get your point.

**Comment by hiqsociety** [comment]
@panjf2000 maybe it's my code. thank you for the verification!
it's mix and matching other go routines. i'll just use yours. thx!
