### ISSUE TITLE
[Question]: Can ants execute tasks in order?

### ISSUE THREAD

**Issue by rts-gordon** [panjf2000/ants#312]
### Questions with details

Hi there,
  Thanks for the ants awesome project, it is very powerful.
  The tasks in pool execute is unordered, it is possible execute tasks in order? 
  
  Thank you.

**Comment by panjf2000** [comment]
Were you talking about executing tasks in serialization? If so, I don't think any pools with concurrency purposes can and should do that. If you want to run your tasks in a strict order, why bother to use a pool? Why not just do it in one goroutine?

On the other hand, if what you wanted is the priority queue, then that's something conceivable, see #59
