### ISSUE TITLE
关于版本问题，我发现小版本(0.0.x)这种更新就会不向下兼容？

### ISSUE THREAD

**Issue by zplzpl** [panjf2000/ants#32]
如题，我感觉这样不好。

功能版本号不向下兼容能理解

修复问题的版本号也不向下兼容，难以理解。

**Comment by panjf2000** [comment]
之前的tag的确不规范，以后我会尽量mini version里修改一些小问题，在major version里才会进行比较大的重构和变更，谢谢指出！
