### ISSUE TITLE
[Bug]: Crashed running this in 192 core cpu aws c6a 384 gb ram cloud instance

### ISSUE THREAD

**Issue by ouvaa** [panjf2000/ants#321]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations on this issue but still have no clue.
- [X] I've searched the current list of Github issues but didn't find any duplicate issues that have been solved.
- [X] I've searched the internet with this issue, but haven't found anything helpful.

### What happened?

try run this and see the crash. not sure if it's because it's 192 cpu core or what...

it says ran out of ram or something but i have 384 gb ram
https://pastebin.com/47FGYhmp

works ok on 12core laptop
can u try this?

### Major version of ants

v2

### Specific version of ants

v2

### Operating system

Linux

### OS version

ubuntu 22.04

### Go version

1.22

### Relevant log output

```shell
sry couldnt capture the whole log

        /root/go/pkg/mod/github.com/panjf2000/gnet@v1.6.7/server_unix.go:68 fp=0xc0958fa7e0 sp=0xc0958fa7d8 pc=0x6e48c0
runtime.goexit({})
        /usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0958fa7e8 sp=0xc0958fa7e0 pc=0x4751c1
created by github.com/panjf2000/gnet.(*server).activateEventLoops.(*server).startEventLoops.func1 in goroutine 59
        /root/go/pkg/mod/github.com/panjf2000/gnet@v1.6.7/server_unix.go:68 +0x85
root@ip-172-31-44-155:/home/ubuntu# Connection to ec2-18-232-98-30.compute-1.amazonaws.com closed by remote host.
```
```


### Code snippets (optional)

_No response_

### How to Reproduce

go build main.go
run inside 192 core aws, crash

### Does this issue reproduce with the latest release?

It can reproduce with the latest release

**Comment by panjf2000** [comment]
I don't think this has anything to do with `ants`, your stack info doesn't look so exhaustive, and it looks more like some issue of `redhub` to me.

Also, I don't think you should spend more time working on `redhub` given that it's a half-baked implementation and it uses an outdated version of `gnet`.

**Comment by ouvaa** [comment]
@panjf2000 thx
