### ISSUE TITLE
[Question]: possible to provide advise on when should we use this gopool vs ants?

### ISSUE THREAD

**Issue by ouvaa** [panjf2000/ants#322]
### Questions with details

1. in what scenario will this be better?
https://github.com/devchat-ai/gopool

2. i've tried the go 1.22.2 normal "go" goroutine. is there still a huge performance difference between ants vs current std lib go routine now? i mean possible to update the benchmark?

**Comment by panjf2000** [comment]
Sorry, I have no advice on how users choose their solution of goroutine-pool. I think you should write some demo code and run some tests yourself, then find out which one is the best fit for your business.
