### ISSUE TITLE
[Question]: 请教一个协程池释放的问题

### ISSUE THREAD

**Issue by shaco-go** [panjf2000/ants#344]
### Questions with details

在默认的协程池里面是不是,释放和不释放没有什么区别
```go
func main(){
  defer ants.Release()
  ants.submit()
}
```
像上面这样,如果我使用的是公共的ants,不考虑可读的话,实际`defer ants.Release()`这句话是不是写于不写没有区别.
因为我想在自己写的一些组件里面去使用ants,有可能在调用方可能不会去主动释放.

**Comment by panjf2000** [comment]
一般来说不用手动释放这个内置的 pool，除非是决定再也不用了。自己创建的 pool 如果不用了也可以 release 掉，虽然一个空 pool 通常来讲不会占用什么资源，但是有机会 release 的话还是 release 掉。
