### ISSUE TITLE
[Question]: NewMultiPool和NewPool大批量任务下推荐使用哪个

### ISSUE THREAD

**Issue by honey-zxy** [panjf2000/ants#345]
### Questions with details

NewMultiPool和NewPool在使用场景上有什么区别呢，我有一个200w+的批量任务，现在使用NewPool来实现，但发现任务开始前期并发上不来，要到后期并发才慢慢上来，导致任务完成耗时不够快，我的需求是需要任务快速跑完，所以需要一开始就能快速提高并发，不知道改为用NewMultiPool会不会有帮助

### Code snippets (optional)
![image](https://github.com/user-attachments/assets/09ffb1db-f09e-4222-8855-54a730a7edca)

_No response_

**Comment by panjf2000** [comment]
你的 Pool 大小是？

**Comment by honey-zxy** [comment]
> 你的 Pool 大小是？有多少个 goroutine 在 submit？

我的任务是单线程任务，只有1个goroutine在执行submit，但pool的大小给的是8000，容器cpu核数配置是12，实际最高才用了5核，cpu利用率才40%，内存利用率约6%。当我尝试调大pool的容量，比如调整成1w，1.2w等，任务的并发数还是没有提升，跟给8000差不读。
![image](https://github.com/user-attachments/assets/a67aeeb9-56d3-40e2-9852-96b38c4fd73f)

**Comment by honey-zxy** [comment]
> 看你的使用场景，我觉得你应该不需要限制并发数量，你可以试试调用 `ants.NewPool(-1)` 创建一个无限制的 pool，只利用 `ants` 的 goroutine 复用特性就行了。

无限制的pool，会导致我的cpu和内存撑爆么，ants内部有默认针对cpu和内存的上限控制么

**Comment by honey-zxy** [comment]
> 看你的使用场景，我觉得你应该不需要限制并发数量，你可以试试调用 `ants.NewPool(-1)` 创建一个无限制的 pool，只利用 `ants` 的 goroutine 复用特性就行了。
无限制pool其实可以通过调大pool容量来模拟，我尝试将容量从8k调到1.5w，发现一个现象，goroutine虽然可以涨到1.5w，但是波动性的，涨了又跌回到0一段时间，不能持续维持在高并发的水平
<img width="1356" alt="image" src="https://github.com/user-attachments/assets/5407a9e6-ef1c-428e-b073-6ce97c12f045" />

**Comment by panjf2000** [comment]
任务执行完了 goroutine 的数量肯定就回落了

**Comment by panjf2000** [comment]
你就直接创建一个无限制大小的 pool 跑一下看看呗。而且我感觉你的要求很奇怪，要用小容量的 pool 限制系统资源的使用，又要在短时间内执行完几百万的任务，这根本就是自相矛盾的。你要么用无限制的 pool，要么就完全不要用，直接每一个任务启动一个 goroutine 去执行。
