### ISSUE TITLE
[Feature]:  Incorrect Comment in ants.go Regarding  workerChanCap Description

### ISSUE THREAD

**Issue by AlvinZGH** [panjf2000/ants#346]
### Description of new feature

Due to the recent version update of fasthttp, the original line numbers no longer correspond to the line numbers for workerChanCap.
![fasthttp](https://github.com/user-attachments/assets/4e6ff2a0-deb2-4df1-b09c-fd8a7b8aff53)

### Scenarios for new feature

Current Text: [https://github.com/valyala/fasthttp/blob/master/workerpool.go#L139]
Suggested Correction: [https://github.com/valyala/fasthttp/blob/v1.58.0/workerpool.go#L158]
Reason for Change: [I believe this change will improve the documentation more accurate]

### Breaking changes or not?

No

**Comment by panjf2000** [comment]
Actually, I don't think we need this comment anymore.
