### ISSUE TITLE
请不要再随意变更版本号了。。。

### ISSUE THREAD

**Issue by choleraehyq** [panjf2000/ants#37]
之前用的是 3.9.9，结果今天构建出了问题，一看发现这个版本没了，变成 1.0.0。这种变更完全不考虑现有用户的情况。希望以后不要随意变更了

**Comment by choleraehyq** [comment]
我现在随便运行什么 module 相关的命令都会报
```
➜  proxybase git:(master) ✗ go mod tidy
verifying github.com/panjf2000/ants@v3.9.9+incompatible/go.mod: github.com/panjf2000/ants@v3.9.9+incompatible/go.mod: reading https://sum.golang.org/lookup/github.com/panjf2000/ants@v3.9.9+incompatible: 410 Gone
```

**Comment by choleraehyq** [comment]
不知道什么地方的缓存缓存了个 3.9.9，我把 pkg/mod 都删了，还是会找到 3.9.9

**Comment by panjf2000** [comment]
真是对不起，因为初期的时候没有严格规划好版本号的迭代，导致版本号混乱，后来想规范起来，所以就清空了以前的tag，详情可以看这里#34，这是我的问题，抱歉。

一开始也考虑到现有用户的影响，但是也只发了一个issue声明，因为没其他途径可以联系用户，以后会严格按照规范来迭代tag，绝对不会发生这种事了，再次抱歉！
