### ISSUE TITLE
带选项的初始化函数，我觉得用 functional options 更好一点

### ISSUE THREAD

**Issue by choleraehyq** [panjf2000/ants#42]
以下是示意代码
如果用 functional options，原来的写法是
```
ants.NewPool(10)
```
新的写法，如果不加 option，写法是不变的，因为 options 是作为可变参数传进去的。如果要加 option，只需要改成
```
ants.NewPool(10, ants.WithNonblocking(true))
```
这样。

现在是直接传一个 Option 结构体进去，所有的地方都要改，感觉很不优雅。
具体 functional options 的设计可以看 rob pike 的一篇博客 https://commandcenter.blogspot.com/2014/01/self-referential-functions-and-design.html

**Comment by choleraehyq** [comment]
另外，按照 go module 的约定，发 v2 大版本应当直接搞一个新的包，panjf2000/ants/v2，而不是发一个 tag v2.0.0。建议改一下

**Comment by panjf2000** [comment]
用 functional options 的话，可能就不需要发布v2了，我看下，thanks.

**Comment by panjf2000** [comment]
Resolved in [v1.3.0](https://github.com/panjf2000/ants/tree/v1.3.0)
