### ISSUE TITLE
关于 <-p.freeSignal 的疑惑

### ISSUE THREAD

**Issue by pathbox** [panjf2000/ants#5]
Hi,
    我阅读了源码，对 `<-p.freeSignal` 这句代码有疑惑。 这句代码出现在了多个地方，freeSignal 的作用英文注释我是理解的，并且知道在 `putWorker` 中才进行 `p.freeSignal <- sig{}`

对于下面的代码
```
func (p *Pool) getWorker() *Worker {
	var w *Worker
	waiting := false

	p.lock.Lock()
	idleWorkers := p.workers
	n := len(idleWorkers) - 1
	if n < 0 { // 说明 pool中没有worker了
		waiting = p.Running() >= p.Cap()
	} else { // 说明pool中有worker
		<-p.freeSignal      
		w = idleWorkers[n]  
		idleWorkers[n] = nil
		p.workers = idleWorkers[:n]
	}
	p.lock.Unlock()


func (p *Pool) Release() error {
	p.once.Do(func() { // 保证只释放一次
		p.release <- sig{}
		p.lock.Lock()
		idleWorkers := p.workers
		for i, w := range idleWorkers {
			<-p.freeSignal
			w.task <- nil
			idleWorkers[i] = nil
		}
		p.workers = nil
		p.lock.Unlock()
	})
	return nil
}

```

中的 `<-p.freeSignal`， 那不是要等putWorker触发了才会继续进行吗？如果 putWorker不触发，就一直阻塞在那了，即使 idleWorkers 中可能是有worker的

可否解释下这边的逻辑？谢谢

**Comment by panjf2000** [comment]
这里freeSignal和idleWorkers的数量是绝对匹配的，也就是说，只要freeSignal有值那么idleWorkers里肯定有可用worker可以取出来，putWorker就是把可用worker放回idleWorkers，每次都会塞一个值进freeSignal，还有每次从idleWorkers里取一个worker都要取出freeSignal对应的一个值，不存在有可用worker却被freeSignal阻塞

**Comment by panjf2000** [comment]
具体问题可以看 #6
