### ISSUE TITLE
workerCache 没有初始化

### ISSUE THREAD

**Issue by choleraehyq** [panjf2000/ants#52]
**Describe the bug**
没有设置 New 函数，这个是忘了还是有什么玄机呢
**To Reproduce**

**Expected behavior**

**Error messages/Trace logs**
If applicable, add some logs to help explain your problem.

**System info (please complete the following information):**
 - OS: [e.g. linux, macOS]
 - Go Version [e.g. 1.12]

**Additional context**

**Comment by panjf2000** [comment]
为什么要设置`New`，我想不到有什么必要性。

**Comment by choleraehyq** [comment]
这个算是个风格问题吧，设了 New 你就不需要写 
```
if cacheWorker := p.workerCache.Get(); cacheWorker != nil {
			w = cacheWorker.(*goWorkerWithFunc)
		} else {
			w = &goWorkerWithFunc{
				pool: p,
				args: make(chan interface{}, workerChanCap),
			}
		}
```
了。我是觉得既然用了 Pool，那用 New 就很自然，像现在这种代码会让人费解，会让人怀疑是不是别的地方会把 nil put 到 Pool 里。

**Comment by panjf2000** [comment]
这个是这样的，设置了`New`之后，调用`workerCache.get()`无法从代码结构上知道得到的 worker 是缓存的还是新建的，这不用`New`而用 if else 之前是想着后面可能会在这个 if 判断的不同分支里做一些其他的东西（虽然到现在好像也还没想到有什么可做的东西），所以其实我倒觉得无所谓了，两种做法都 ok 😂

**Comment by choleraehyq** [comment]
ok， 那我就 close
