### ISSUE TITLE
非阻塞在PoolOverload时进入等待队列

### ISSUE THREAD

**Issue by HaoKunT** [panjf2000/ants#56]
**Is your feature request related to a problem? Please describe.**
submit的函数如果是递归函数，则如果是阻塞模式，在递归深度较大的时候，会因为worker用光，程序直接被阻塞了，如果调整为非阻塞模式，则会在worker用光之后，后面的任务直接返回ErrPoolOverload而被舍弃。我是在遍历目录的时候遇到的这个问题。

**Describe the solution you'd like**
增加一个配置项，非阻塞模式下，可以选择增加一个等待队列，而不是舍弃。

**Describe alternatives you've considered**
增加一个channel，用于task完成后通知等待队列

**Comment by panjf2000** [comment]
为什么递归会用完 worker ？

**Comment by HaoKunT** [comment]
对，就是我遍历目录的时候，每一个子目录就再`pool.Submit`，就像这样子
``` go
               if !cextinfo.IsDir() {
			// ...
		} else {
			wg.Add(1)
			err = p.Submit(func() {
				buildTree(&cextinfo, errs, wg, p)
				wg.Done()
			})
			if err != nil {
				errs <- err
		}
```

**Comment by panjf2000** [comment]
你这个需求和 #55 大同小异，都是想把业务特性加到 `ants` 里，不太妥当。再说，是不是你的 pool size 设置得太小了？设置个几十万难道还不能满足？遍历的目录是有多大？

**Comment by HaoKunT** [comment]
你说的有道理，但是如果长度无限制的话，那和自带的go关键字似乎没有区别？实际上我使用ants的原因就是在遍历很大的目录的时候，会出现内存占用过多的情况，因此希望能复用go程，那个`ExpiryDuration`配置项具体起到什么作用啊？是不是这个会隔一段时间就清理一次？是什么原理？

**Comment by panjf2000** [comment]
> 但是如果长度无限制的话，那和自带的go关键字似乎没有区别？实际上我使用ants的原因就是在遍历很大的目录的时候，会出现内存占用过多的情况，因此希望能复用go程

有区别啊，`ants` 虽然长度无限，但是会有复用，一旦 worker 完成任务就可以给下一个任务用，所以虽然你设置的是很大的 size，但是实际上整个流程跑完，最终创建的 go 程的数量可能是很少的，你可以试试。

> 那个ExpiryDuration配置项具体起到什么作用啊？是不是这个会隔一段时间就清理一次？是什么原理？

`ExpiryDuration` 就是一个定时的周期，就表示每隔 `ExpiryDuration` 时长执行一次清理，清理掉那些放置在队列里超过 `ExpiryDuration` 没有被使用过的 worker，以此类推。。。

**Comment by HaoKunT** [comment]
OK懂了，谢谢
