### ISSUE TITLE
请问 bytedance 的什么项目使用了 ants？

### ISSUE THREAD

**Issue by choleraehyq** [panjf2000/ants#57]
看 readme 里写了 bytedance

**Comment by panjf2000** [comment]
我看你之前说在线上使用了 `ants`，我还以为是贵司在用，是我误会了？😂

**Comment by choleraehyq** [comment]
我并没有说过 bytedance 线上在用 ants。。。

**Comment by panjf2000** [comment]
哦哦，那是我误会了，等会儿我更新一下 README，移掉 logo，抱歉！
