### ISSUE TITLE
goroutine 不是协程，项目描述不准确。

### ISSUE THREAD

**Issue by choleraehyq** [panjf2000/ants#60]
**Describe the bug**

目前的项目描述里提到，“ ants 是一个高性能且低损耗的 goroutine 协程池。”，这个说法是不正确的，goroutine 不是协程。

首先，goroutine 不是我们通常说的协作式调度，绝大部分的 go 程序都是没有 runtime.Gosched 的。如果认为 go scheduler 内部的抢占调度目前不完善，那 linux 内核在 2.几 某个版本之前也没有完善的抢占调度，难道 linux 线程也是协程吗。

另外，预期 Go 1.14 就有完全的抢占调度了，更跟协程不搭边了。

**To Reproduce**

**Expected behavior**

**Error messages/Trace logs**
If applicable, add some logs to help explain your problem.

**System info (please complete the following information):**
 - OS: [e.g. linux, macOS]
 - Go Version: [e.g. 1.12]
 - ants version: [e.g. v2.2.2]

**Additional context**

**Comment by panjf2000** [comment]
首先谢谢提醒，其次，我知道 goroutine 并不是协程，从 goroutine 是并发的就可以明确它不是协程了，只是当初在推广的时候为了让那些不熟悉 go 的人能有个粗浅的轮廓才这么写的，毕竟直接说 goroutine 很多人不熟悉，说实话的确是一种挺懒的做法。。。
不过我最早的关于 `ants` 的博客已经写得很清楚了，goroutine 不是传统意义上的协程。

不过你倒是提醒我了，README 里的这部分用语的确得更新一下了，到时候修正了之后我再 close 掉这个 issue。

**Comment by chengyayu** [comment]
@choleraehyq @panjf2000 请问为何说 goroutine 不是协程？如果 goroutine 不是，符合什么特征的可并发执行体可以被称之为协程？

**Comment by kingreatwill** [comment]
@choleraehyq @panjf2000   goroutine 是goroutine我知道，那么goroutine 是什么？

**Comment by panjf2000** [comment]
![image](https://user-images.githubusercontent.com/7496278/78556577-cc0f8d00-7841-11ea-9ec4-1c5e5dc9ac25.png)

最主要的区别是调度方式，一个是协作式，一个是抢占式，而且本质上协程做不到并行，只能是并发，还有就是协程是不需要同步原语：锁、信号量等这些，因为不存在临界区。

至于说 goroutine 到底是什么，我个人觉得可以称之为**轻量的用户级线程**。

@chengyayu @kingreatwill

**Comment by kingreatwill** [comment]
好的谢谢！官网确实明确说明了
![image](https://user-images.githubusercontent.com/13087689/78620179-dd907d80-78b1-11ea-872d-8ef805f5a9fa.png)
