### ISSUE TITLE
go1.8无法运行benchmark测试

### ISSUE THREAD

**Issue by Kuching** [panjf2000/ants#63]
你好，我的本地环境和生产环境都是go1.8，目前通过go get会报cannot find package "github.com/panjf2000/ants/v2/internal”错误，而go1.8还不支持go modules。
想问一下这个代码需要做哪些变动才可以运行在go1.8上呢？你们可以提供支持么？
谢谢~ #62

**Comment by panjf2000** [comment]
那你就直接 `go get github.com/panjf2000/ants` 就是最新的代码了。
