### ISSUE TITLE
internal.NewSpinLock about runtime.Gosched()

### ISSUE THREAD

**Issue by jjshi** [panjf2000/ants#65]
I see that internal.NewSpinLock() is internal Lock. Why don't use sync.Mutex?
runtime.Gosched() is put current goroutine to global run queue tail.
Hope your response.

**Comment by panjf2000** [comment]
The reason why I chose spinlock over mutex is that the goroutine would be put into wait queue and awaked once the lock is released with mutex but most of the cases with `ants` won't hold the lock long time, so all those actions with mutex seem to be unnecessary and there will be a higher performance with spinlock.

**Comment by panjf2000** [comment]
@jjshi 
Do you still have questions about this? or other questions?

**Comment by jjshi** [comment]
thanks @panjf2000
