### ISSUE TITLE
worker的task问题

### ISSUE THREAD

**Issue by LiangXu1992** [panjf2000/ants#68]
我初略的看了一下启动的过程，有几个疑问想请教一下
在newpool之后，想要执行任务需要调用pool的submit。在submit里面，有一段代码是w.task <- task.
w是worker的意思，但worker的task chan长度只有1，所以有并发任务来的时候，都在抢占这个w.task。要怎么保证任务的先后顺序的？

**Comment by panjf2000** [comment]
首先，每个人 task 抢占的不是 w.task 这个 chan，抢占的是 w，每一个 w 只会处理一个 task；其次，`ants` 并不保证提交的任务的顺序，README上页说明了：
[about sequence](https://github.com/panjf2000/ants#%EF%B8%8F-about-sequence)

**Comment by LiangXu1992** [comment]
ok...没看readme

**Comment by LiangXu1992** [comment]
thx
