### ISSUE TITLE
提两个小需求

### ISSUE THREAD

**Issue by bglmmz** [panjf2000/ants#69]
1. 在批量提交任务后，获取每个任务对应的返回值.
2. 在批量提交任务时，可以携带一个超时参数，表示这批任务执行时，如果超时，则已执行的任务正常返回执行结果，未执行的任务都提前结束（或也返回执行结果，但是标明是timeout）。

**Comment by bglmmz** [comment]
NewPoolWithFunc()里的func，只能一个参数吗？

**Comment by panjf2000** [comment]
那个参数是 interface, 你要是想带多个的话，直接传一个 array 或者 slice 进去，然后在函数里还原一下不就行了吗？

**Comment by panjf2000** [comment]
> 在批量提交任务后，获取每个任务对应的返回值.

提交任务之后是异步执行的，没法同步返回。

**Comment by bglmmz** [comment]
> 那个参数是 interface, 你要是想带多个的话，直接传一个 array 或者 slice 进去，然后在函数里还原一下不就行了吗？

明白

**Comment by panjf2000** [comment]
还有关于多个参数的问题，其实也可以直接用那个无参的方法，然后你通过闭包引用的方式操作多个参数，还省去了转换的操作。

**Comment by bglmmz** [comment]
> 交任务之后是异步执行的，没法同步返回。

现在这个工具把执行线程池化了，但是任务没有队列化吗？

**Comment by bglmmz** [comment]
如果我有100万个任务，如何用10个线程的线程池来异步执行呢？用ants.WithMaxBlockingTasks这参数？此参数设置100万？

**Comment by panjf2000** [comment]
你就直接设置 size=10 就行了。

**Comment by bglmmz** [comment]
> 你就直接设置 size=10 就行了。
那剩下的任务都会阻塞着等待submit进去执行吗？

**Comment by daydreamjfhu** [comment]
我觉得第一个问题说的是，如何把线程池任务的结果带回给线程池的调用者，如果你传指针或者引用类型，是不是涉及都了并发操作？

**Comment by tong3jie** [comment]
> 还有关于多个参数的问题，其实也可以直接用那个无参的方法，然后你通过闭包引用的方式操作多个参数，还省去了转换的操作。

是不是这样的?

```
func A(a string) func() string {
	return func() string {
		return a
	}
}
f := A("a")
pool.Submit(f)
```
