### ISSUE TITLE
清理过期协程报错

### ISSUE THREAD

**Issue by huiwq1990** [panjf2000/ants#7]
你好，非常感谢提供这么好用的工具包。我在使用ants时，发现报异常。结果见下图
![image](https://user-images.githubusercontent.com/4555057/43823431-98384444-9b21-11e8-880c-7458b931734a.png)
日志是我在periodicallyPurge里加的调试信息
![image](https://user-images.githubusercontent.com/4555057/43823534-e3c624a8-9b21-11e8-96c6-512e3e08db22.png)

### 原因分析

我认为可能原因是没有处理n==0的情况
```
if n > 0 {
	n++
	p.workers = idleWorkers[n:]
}
```

### 测试代码
```
package main

import (
	"github.com/panjf2000/ants"
	"fmt"
	"time"
	"strconv"
)

func main() {

	pool,err := ants.NewPool(100000)

	if err != nil {
		panic(err)
	}

	for i:=0;i<10000;i++{
		pool.Submit(
			func() error {
				time.Sleep(1 * time.Millisecond)
				fmt.Println(strconv.Itoa(i))
				return nil
			})
	}

	for{
		pool.Submit(
			func() error {
				time.Sleep(10 * time.Millisecond)
			return nil
		})
		time.Sleep(1 * time.Millisecond)
	}
}
```

**Comment by panjf2000** [comment]
@huiwq1990 谢谢指出，今天会修复这个问题。

**Comment by panjf2000** [comment]
@huiwq1990 应该解决了，可以再试试

**Comment by huiwq1990** [comment]
嗯，解决了

**Comment by panjf2000** [comment]
@huiwq1990 好的，那我关掉这个issue了。
