### ISSUE TITLE
关于retrieveWorker中一小段代码的疑问

### ISSUE THREAD

**Issue by HobbyBear** [panjf2000/ants#70]
```go
if n >= 0 {
		w = idleWorkers[n]
		idleWorkers[n] = nil
		p.workers = idleWorkers[:n]
		p.lock.Unlock()
	} else if p.Running() < p.Cap() {
		p.lock.Unlock()
		spawnWorker()
	} else {
		if p.nonblocking {
			p.lock.Unlock()
			return nil
		}
```
 if p.Running() < p.Cap() 判断以后符合条件解锁，再重新创建worker，worker会在run的时候才进行running数的加1会不会有worker在run的时候让出cpu，此时另一个协程执行到p.Running() < p.Cap()判断也符合，从而导致最终的running其实是大于cap的情况呢

**Comment by panjf2000** [comment]
@HobbyBear 
的确存在这种情况，偶尔会发生 running goroutines 数量轻微溢出 capacity 的值，但是这种提前释放锁而导致的溢出并不是什么大问题：
1. 首先这种情况发生的概率极小，之所以提前释放锁是为了让其他的 go 程能更快地取回 workers，提高性能，如果是整个过程都锁住的确可以保证不溢出，但是为了这种极小概率的事件而损耗大部分场景的性能有点得不偿失；
2. 其次就算发生了这种情况，溢出的 goroutines 数量也只会是极小的，至少是在可接受的范围内，而且在 workers 完成任务后归还 pool 的时候也会进行[检查](https://github.com/panjf2000/ants/blob/master/pool.go#L245)，舍弃掉溢出的 goroutines，从而慢慢还原至 pool capacity，所以从局部来看，pool 里的 workers 不是完全小于等于容量的，但从整体来看是无限趋近的。

**Comment by HobbyBear** [comment]
好的，感谢分享

**Comment by panjf2000** [comment]
还有什么问题？
