### ISSUE TITLE
如何限制httpserver的最大协程数

### ISSUE THREAD

**Issue by 914795561** [panjf2000/ants#71]
与httpserver集成好像并没能解决内置http包来一个请求开一个goroutine的问题，请问该如何限制内置http包的最大协程数呢？

**Comment by panjf2000** [comment]
内置 http 那种每个请求一个 goroutine 的是没法从外部限制的，那是源码级别的模式了，README 上的例子只能限制一个请求的 goroutine 里再新创建的其他 goroutines。
