### ISSUE TITLE
how to wait for completion

### ISSUE THREAD

**Issue by vtolstov** [panjf2000/ants#73]
I need graceful shutdown of my app with ants.PoolWithFunc so i need firstly forbid new tasks, and second wait for completion of already running. How can i do that with ants ?

**Comment by panjf2000** [comment]
> i need firstly forbid new tasks

Use an atomic counter to record your running tasks also block new tasks.

> and second wait for completion of already running

I think `WaitGroup` is the answer you were looking for.

**Comment by vtolstov** [comment]
did you mind to add this to "core" ants? or this is user decision? I'm prefer to have this via set capacity of pool to zero. So new tasks can't be scheduled, older - continue to run

**Comment by panjf2000** [comment]
The functionality of blocking new task could be added to `ants` but the other one of waiting for all tasks can't and shouldn't be added, because `ants` ought to have the same behaviors like the `go` statement.

**Comment by vtolstov** [comment]
Ok, thanks. May be i can add some pooling and if wait provided - recheck busy workers?
Do you have some timeline for blocking adding new tasks?

**Comment by panjf2000** [comment]
> Do you have some timeline for blocking adding new tasks?

I think there is a quite easy way to do that for adding one more check here: [a](https://github.com/panjf2000/ants/blob/master/pool_func.go#L161) and [b](https://github.com/panjf2000/ants/blob/master/pool.go#L142), like:
```go
if p.Cap() == 0 {
    return Errxxx
}
```
I will do it on my own sometime tomorrow but if you are interested in it, you are welcome to submit a PR for it.

**Comment by panjf2000** [comment]
BTY, releasing the pool also blocks new tasks, does that meet your requirements? if so, then it is no need to add new functionality any more.

**Comment by vtolstov** [comment]
May be this is what i need. How ants works if i do Release on pool and try to add new task with Blocking/Nonblocking mode? And if some task already running and i'm run Release?

**Comment by panjf2000** [comment]
Once you invoke `p.Release()`, it is going to close all idle workers while it has no impact on those workers that are running tasks. Besides, those running workers will exit automatically after they finish their tasks.

But you should note that the pool can't be reopened once you release it.

**Comment by vtolstov** [comment]
This is not problem. So thanks for your time, i'm try use Release. So only needed modification is blocking for new tasks. I'm try to prepare pr for this.

**Comment by vtolstov** [comment]
nothing needs to be changed. thanks for great library
