### ISSUE TITLE
periodicallyPurge可以考虑recover捕获一下panic

### ISSUE THREAD

**Issue by Andrewpqc** [panjf2000/ants#74]
**What is your question about ants?**
Please describe your question meticulously.
虽然看了一下这个函数没可能painc,但是开启goroutine不recover让人心慌。

**Comment by panjf2000** [comment]
谢谢你的提醒，但也正像你说的，`periodicallyPurge` 发生 panic 的可能性极小，现在唯一可能导致 panic 的地方是这里：
https://github.com/panjf2000/ants/blob/d3e44612e2420872307f1c320e15928c536db4fb/pool.go#L76
这是 worker 队列的接口，留给后面添加新 worker 队列类型用的，目前来说现有的两种队列实现基本不可能导致 panic，所以我暂时不考虑加 recover，因为现在加除了导致代码测试覆盖率下降之外没有任何实际的好处，过早优化是万恶之源嘛！
等以后添加新的队列类型之后且可能导致 panic了，我再慢慢考虑加这个。

**Comment by Andrewpqc** [comment]
顺便问一句，amazon招人吗?

**Comment by panjf2000** [comment]
抱歉，我已经不在那里了。

**Comment by Andrewpqc** [comment]
现在在哪上班呢？有兴趣来字节吗？
