### ISSUE TITLE
能否中断未执行完成的任务？

### ISSUE THREAD

**Issue by bglmmz** [panjf2000/ants#82]
我创建了一个PoolWithFunc
然后通过一个for循环，用pool.Invoke()来执行任务
我的需求是：我所有的任务有一个统一的deadline，超过就需要让所有任务退出（包括正在执行但是未执行完成，以及还未开始执行的）

请问，用这个ants能实现这个吗？

谢谢！

**Comment by panjf2000** [comment]
你这个需求只能在你自己的 func 里用 timer + channel + signal 来解决了，目前 ants 不支持这样的特性。

**Comment by bglmmz** [comment]
查了些资料，goroutine好像是没办法中断的。
