### ISSUE TITLE
pool.Release 不能干掉繁忙的协程哦

### ISSUE THREAD

**Issue by jp3411952** [panjf2000/ants#85]
**What is your question about ants?**
Please describe your question meticulously.
可以将task设置为接口,pool释放的时候主动通知task 结束 任务，释放协程

**Comment by panjf2000** [comment]
调用 Release 之后，会把当前空闲的 workers 释放掉，但是还在执行任务的则会在结束任务之后自动释放掉，我觉得这样就可以了，没必要强制结束正在运行的 workers，你的提议和目前的架构差别有点大，暂时不考虑，谢谢！
