### ISSUE TITLE
v2.PoolWithFunc has no field or method Serve

### ISSUE THREAD

**Issue by huangp0600** [panjf2000/ants#88]
I encounter some build problems, hinting "myPool.Serve undefined (type *v2.PoolWithFunc has no field or method Serve)"

```
import (
	"fmt"
	"strconv"
	"time"
	"github.com/panjf2000/ants/v2"
)


var tunnel = make(chan string, 1)
func main() {

	//push something to tunnel

	myPool, _ := ants.NewPoolWithFunc(3, Myfunc)
	defer myPool.Release()

	for {
		select {
		case a := <-tunnel:
			go myPool.Serve(a)
		}
	}
}

```

**Comment by panjf2000** [comment]
Which version of `ants` were you using? There is already no `Serve` method in v2, it is `Invoke` now, please read the doc more carefully.

**Comment by panjf2000** [comment]
BTY, you are using `ants` in a wrong way, there is no need to submit a task to pool in a new goroutine, you're already using a goroutine pool, why did you still have to use `go` to submit task to pool, it makes no sense here, just call pool.Invoke directly.

**Comment by huangp0600** [comment]
Thanks for quick response. Ants provides a great experience when writing concurrent code. 
I have another question,
if Myfunc has more than one parameters, how should I call `myPool, _ := ants.NewPoolWithFunc(3, Myfunc)`?
I checked the declaration of NewPoolWithFunc, it seems like `pf `only accept one parameter.

> func NewPoolWithFunc(size int, pf func(interface{}), options ...Option) 

thanks in advance

```
import (
	"fmt"
	"strconv"
	"time"
	"github.com/panjf2000/ants/v2"
)


var tunnel = make(chan string, 1)
func main() {

	//push something to tunnel

	myPool, _ := ants.NewPoolWithFunc(3, Myfunc)
	defer myPool.Release()

	for {
		select {
		case a := <-tunnel:
			myPool.Invoke(a)
		}
	}
}

```

**Comment by panjf2000** [comment]
#81
