### ISSUE TITLE
希望能够支持一个小特性

### ISSUE THREAD

**Issue by 1046102779** [panjf2000/ants#92]
1.  PoolWithFunc希望能够支持任务池的名称；这样一个server存在多个任务池，方便定位问题；
2. PoolWithFunc中的Invoke方法返回error，希望能区分是非阻塞队列任务池满的error msg，还是阻塞队列都满的error msg错误区分，目前笼统地称为：ErrPoolOverload, 这个不太方便定位问题。

**Comment by panjf2000** [comment]
> 1. PoolWithFunc希望能够支持任务池的名称；这样一个server存在多个任务池，方便定位问题；

加名字具体怎么帮助你定位问题？你是想在 worker 发生 panic 之后打印的 log 里打印出名字？

> 2. PoolWithFunc中的Invoke方法返回error，希望能区分是非阻塞队列任务池满的error msg，还是阻塞队列都满的error msg错误区分，目前笼统地称为：ErrPoolOverload, 这个不太方便定位问题。

阻塞池满了是会一直阻塞的，除非你设置了 MaxBlockingTasks

**Comment by panjf2000** [comment]
太长时间没回复，暂时关闭该 issue，如果还有问题可以重新打开。
