### ISSUE TITLE
使用过程中遇到的一个比较棘手的问题

### ISSUE THREAD

**Issue by 1046102779** [panjf2000/ants#93]
我在使用过程中，如果一个serve部署在异构环境中，可能我设置的任务池大小，就不太适用，要么资源打满，要么资源利用率相对比较低，能根据当前cpu和内存使用情况自动动态的调整任务池大小不？

**Comment by panjf2000** [comment]
`ants` 有提供动态调整 pool capacity 的接口啊：https://github.com/panjf2000/ants#tune-pool-capacity-in-runtime

**Comment by panjf2000** [comment]
太长时间没回复，暂时关闭该 issue，如果还有问题可以重新打开。

**Comment by dragon-zhang** [comment]
@1046102779 老哥，你是不是想让`ants`根据当前系统负载，自适应动态调节协程池的大小？
