### ISSUE TITLE
可以对某个groutine进行操作吗？（比如手动终止某个groutine）

### ISSUE THREAD

**Issue by resct** [panjf2000/ants#96]
**What is your question about ants?**
Please describe your question meticulously.
潘神，我看了下你写的代码，里面没有对单个groutine的控制？（我Go接触不久，或者我有遗漏的地方？）

网上搜了一下，Go好像没办法像Java对线程的操作一样，对Groutine进行直接的控制，很多都是间接操作的。

1.那如果需要这样做，该怎么弄呢？ 有解决方案吗？（潘神有相关的思路吗）

2.groutine里嵌套groutine,这种又该怎么处理？

**Comment by chenjsa** [comment]
context

**Comment by resct** [comment]
> context

嗯   我也正在看context的内容，从我目前了解的来看，很多都是类似这样处理的 ：
select {
		case <-ctx.Done():
			//Do something
		default:
			//Do something
}

现在出现的情况是，比如：

1.  A->B->C->D  四个groutine   中途发现B出现问题，占用CPU过高，想终止掉，也不想C、D执行

2.A执行过程，需要起B、C、D  三个groutine    中途发现出现问题，占用CPU过高，想定位到是哪个groutine出现的问题，然后进行各项操作（也就是能够监控这些groutine）

context中   我进行cancel，子groutine 还是会执行完  感觉cancel好像没什么作用一样

我再继续看下相关的内容，看下是否有没理解清或者遗漏的地方

**Comment by resct** [comment]
我看了下   Go是无法从外部直接控制goroutine的生命周期的？？？

**Comment by resct** [comment]
> context是可以派生的。 父context被终止或者超时，会传导下去。

通过WithCancel, WithDeadline, WithTimeout或者WithValue去派生出子context来传递？

我之前测试用了WithCancel，但当我  cancel的时候，子groutine还是在执行，直到结束（我测试代码写的有误吗？）

有相关的测试代码方便参考吗？

**Comment by solarhell** [comment]
自己在routine里监听呀 就是那个select case 然后对应清理 return 不就是关掉了routine吗

**Comment by resct** [comment]
> 自己在routine里监听呀 就是那个select case 然后对应清理 return 不就是关掉了routine吗

抱歉，可能是我表诉的有问题。
我指的是用select或者其他方式在代码中加判断的， 不是得groutine的代码执行到判断的时候，才能退出？   我现在是想任意时候退出，就像直接kill掉这个groutine一样

**Comment by panjf2000** [comment]
你这个问题和 `ants` 有什么关系？
@resct

**Comment by resct** [comment]
ants中有相关对groutine的API操作吗？ 或者本身Go就是没有相关操作的？ 
我刚接触Go没多久，可能问的问题比较小白
（不相关的话，我等下把自己的那部分issue清了，在关闭issue就行了，抱歉耽误大家时间了）

**Comment by panjf2000** [comment]
> ants中有相关对groutine的API操作吗？ 有相关知识可以分享的吗？

`ants` 是一个 worker 模式的 goroutine pool，适用场景是大量的一次性任务，每个任务会附到一个 worker 里去执行，你的需求和 `ants` 没啥关系，你需要在 goroutine 里监听等待主进程的信号，也就是说会长时阻塞等待，那也是类似 worker 模式了，这种任务就不适宜提交到 `ants` 里了，worker 套 worker，没有意义，利用 buffered channel 做一下简单的限制 goroutine 数量就行了。

正如我前面所说，`ants` 并不是操作控制 goroutine 的库，仅仅是执行提交的任务，所以你这问题的确和 `ants` 没有关系，我准备关掉了。

至于你说的控制 goroutine，前面已经有同学回答你了，Context 可以做到，但是你一直说想直接 kill 掉，那你就用信号去做吧，go 也有相关的标准库可以用，直接 google 一下就行。

最后，下次这种技术问题请直接到相关的论坛/社区去提问，Github issue 是用来解决开源库相关问题的，不是泛技术问题的讨论区。

@resct

**Comment by resct** [comment]
> > ants中有相关对groutine的API操作吗？ 有相关知识可以分享的吗？
> 
> `ants` 是一个 worker 模式的 goroutine pool，适用场景是大量的一次性任务，每个任务会附到一个 worker 里去执行，你的需求和 `ants` 没啥关系，你需要在 goroutine 里监听等待主进程的信号，也就是说会长时阻塞等待，那也是类似 worker 模式了，这种任务就不适宜提交到 `ants` 里了，worker 套 worker，没有意义，利用 buffered channel 做一下简单的限制 goroutine 数量就行了。
> 
> 正如我前面所说，`ants` 并不是操作控制 goroutine 的库，仅仅是执行提交的任务，再说了，文档里有所有的接口，你如果看完就可以知道是没有什么控制 goroutine 的 API 的，所以你这问题的确和 `ants` 没有关系，我准备关掉了。
> 
> 至于你说的控制 goroutine，前面已经有同学回答你了，Context 可以做到，但是你一直说想直接 kill 掉，那你就用信号去做吧，go 也有相关的标准库可以用，直接 google 一下就行。
> 
> 最后，下次这种技术问题请直接到相关的论坛/社区去提问，Github issue 是用来解决开源库相关问题的，不是泛技术问题的讨论区。
> 
> @resct

好的，感谢！！！
