### ISSUE TITLE
SECURITY ERROR: checksum mismatch

### ISSUE THREAD

**Issue by navid-kalaei** [panjf2000/ants#97]
**Description**
Mismatched checksum

**To Reproduce**
Run `go get https://github.com/panjf2000/ants`

Or
1. Import `"github.com/panjf2000/ants"`
1. Run `go mod vendor`

**Expected behavior**
Successful installation of ants as a vendor/dependency

**Error messages/Trace logs**
go get github.com/panjf2000/ants: github.com/panjf2000/ants@v1.2.0: verifying module: checksum mismatch
        downloaded: h1:Ufw4aDz9RqH1RVblx2W9L9Uv5vSX5apbX5+peR7LQ5k=
        sum.golang.org: h1:pMQ1/XpSgnWx3ro4y1xr/uA3jXUsTuAaU3Dm0JjwggE=

**System info (please complete the following information):**
 - OS: 4.15.0-23-generic #25-Ubuntu
 - Go Version: go1.14 linux/amd64
 - ants version: v1.2.0

**Additional context**
SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

**Comment by panjf2000** [comment]
Does #49 help?

**Comment by navid-kalaei** [comment]
Thank you so much.

`go clean -modcache`

works nicely! :tada:
