### ISSUE TITLE
pool.Tune does not take effect if the pool is preallocated

### ISSUE THREAD

**Issue by giangvu** [panjf2000/ants#98]
Hello,

May I know the reason behind the p.options.PreAlloc check? 
https://github.com/panjf2000/ants/blob/master/pool.go#L173
`if capacity := p.Cap(); capacity == -1 || size <= 0 || size == capacity || p.options.PreAlloc {
	return
}`

Why can't we tune the pool if it is preallocated?

Thanks.

**Comment by panjf2000** [comment]
> Why can't we tune the pool if it is preallocated?

Because supporting `Tune(int)` under `Pre-Alloc` mode will result in allocating a vast amount of new memories and copying a large number of workers, not reusing memories like the non-preallocate mode.
